/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhuyenMai;

import DTO.ChiTietKhuyenMaiDTO;
import DTO.ChiTietKhuyenMaiDTO;
import DTO.ChuongTrinhKhuyenMaiDTO;
import DTO.DonHangDTO;
import static GUI.KhuyenMai.ChuongTrinhKhuyenMaiJPanel.listTableModel;
import static GUI.KhuyenMai.ThongTinChuongTrinhKhuyenMaiJPanel.currentDonHangList;
import GUI.KhuyenMaiJPanel;
import GUI.Sweet.SweetComboBox;
import GUI.Table.RenderTable;
import static GUI.TongQuanJPanel.customTable;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import quanlycuahangsach.DateTime;

/**
 *
 * @author admin
 */
public class ChiTietKhuyenMaiJPanel extends javax.swing.JPanel {
    static ChiTietKhuyenMaiDTO currentChiTietKhuyenMai;
    static ArrayList<DonHangDTO> currentDonHangList;
     SweetComboBox cbxTrangThai;
    public ArrayList<ChiTietKhuyenMaiDTO> arraySearch;
    /**
     * Creates new form ChiTietKhuyenMaiJPanel
     */
    Object[] columnNames ={"Mã chương trình KM","Mã chi tiết KM","Mã khuyến mãi","Số lượng","Còn lại","Ngày tạo","Ngày bắt đầu"};
    static DefaultTableModel listTableModel;
    /**
     * Creates new form KhuyenMaiJPanel
     */
    public void setComboBox(){
         String[] trangthai = {"Tất cả","Còn","Hết"};
        cbxTrangThai = new SweetComboBox("#CAE5F6","#181818",0,0,120,30,trangthai);
        pnlTrangThai.add(cbxTrangThai);  
        cbxTrangThai.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent ie){
                getAdvancedSearch();
            }
        });
    }         
    public void ShowTable(JTable table,Object[] columnName){
        
        table.setDefaultRenderer(Object.class, new RenderTable());
        listTableModel = new DefaultTableModel(columnNames,0);
        fetchAll();
    }  
    public static void fetchAll(){
    listTableModel.setRowCount(0);
        quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.ChiTietKhuyenMaiList.forEach(ChiTietKhuyenMai -> {
            Vector row = new Vector();
            row.add(ChiTietKhuyenMai.getMaChuongTrinhKhuyenMai());
            row.add(ChiTietKhuyenMai.getMaChiTietKhuyenMai());
            row.add(ChiTietKhuyenMai.getMaCode());
            row.add(ChiTietKhuyenMai.getSoLuong());
            row.add(Integer.parseInt(ChiTietKhuyenMai.getSoLuong())-Integer.parseInt(ChiTietKhuyenMai.getSoLuongDaDung()));
            row.add(DateTime.TimestampToDateString(ChiTietKhuyenMai.getThoiGianBatDauSuDung(),0));
            row.add(DateTime.TimestampToDateString(ChiTietKhuyenMai.getThoiGianKetThucSuDung(),0));
            listTableModel.addRow(row);
        });
        tblChiTietKhuyenMai.setModel(listTableModel);
    
    
    }
    public void setShadow(){
        pnlTblDonHangChuaXacNhan.setShadow(1);
    }
     
    public ChiTietKhuyenMaiJPanel() {
        initComponents();
        customTable(tblChiTietKhuyenMai,scpChiTietKhuyenMai);
        ShowTable(tblChiTietKhuyenMai,columnNames);
        tblChiTietKhuyenMai.getTableHeader().setFont(new Font("SansSerif", Font.PLAIN, 12));
        pnlTaoChiTiet.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setComboBox(); 
        setShadow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaChiTiet = new javax.swing.JLabel();
        lblMaKhuyenMai = new javax.swing.JLabel();
        pnlTimKiemTenChuongTrinh = new GUI.Rounded();
        txtTimKiemMaKhuyenMai = new javax.swing.JTextField();
        pnlTimKiemMaChuongTrinh = new GUI.Rounded();
        txtTimKiemMaChuongTrinh = new javax.swing.JTextField();
        pnlTaoChiTiet = new GUI.Rounded();
        lblTaoPhieuNhap = new javax.swing.JLabel();
        pnlTblDonHangChuaXacNhan = new GUI.Rounded();
        scpChiTietKhuyenMai = new javax.swing.JScrollPane();
        tblChiTietKhuyenMai = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();
        lblTitleTrangThai = new javax.swing.JLabel();
        pnlTrangThai = new javax.swing.JPanel();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaChiTiet.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblMaChiTiet.setForeground(new java.awt.Color(0, 52, 102));
        lblMaChiTiet.setText("Mã chương trình:");
        add(lblMaChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        lblMaKhuyenMai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblMaKhuyenMai.setForeground(new java.awt.Color(0, 52, 102));
        lblMaKhuyenMai.setText("Mã chi tiết:");
        add(lblMaKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        pnlTimKiemTenChuongTrinh.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemTenChuongTrinh.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemTenChuongTrinh.setFocusable(false);

        txtTimKiemMaKhuyenMai.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemMaKhuyenMai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaKhuyenMai.setBorder(null);
        txtTimKiemMaKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemMaKhuyenMaiActionPerformed(evt);
            }
        });
        txtTimKiemMaKhuyenMai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaKhuyenMaiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemTenChuongTrinhLayout = new javax.swing.GroupLayout(pnlTimKiemTenChuongTrinh);
        pnlTimKiemTenChuongTrinh.setLayout(pnlTimKiemTenChuongTrinhLayout);
        pnlTimKiemTenChuongTrinhLayout.setHorizontalGroup(
            pnlTimKiemTenChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemTenChuongTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );
        pnlTimKiemTenChuongTrinhLayout.setVerticalGroup(
            pnlTimKiemTenChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemTenChuongTrinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemTenChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 470, -1));

        pnlTimKiemMaChuongTrinh.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemMaChuongTrinh.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemMaChuongTrinh.setFocusable(false);

        txtTimKiemMaChuongTrinh.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemMaChuongTrinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaChuongTrinh.setBorder(null);
        txtTimKiemMaChuongTrinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaChuongTrinhKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemMaChuongTrinhLayout = new javax.swing.GroupLayout(pnlTimKiemMaChuongTrinh);
        pnlTimKiemMaChuongTrinh.setLayout(pnlTimKiemMaChuongTrinhLayout);
        pnlTimKiemMaChuongTrinhLayout.setHorizontalGroup(
            pnlTimKiemMaChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemMaChuongTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlTimKiemMaChuongTrinhLayout.setVerticalGroup(
            pnlTimKiemMaChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemMaChuongTrinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemMaChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 470, -1));

        pnlTaoChiTiet.setBackground(new java.awt.Color(238, 243, 247));
        pnlTaoChiTiet.setForeground(new java.awt.Color(0, 146, 242));
        pnlTaoChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaoChiTietMouseClicked(evt);
            }
        });

        lblTaoPhieuNhap.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTaoPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTaoPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaoPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        lblTaoPhieuNhap.setText("Tạo chi tiết");

        javax.swing.GroupLayout pnlTaoChiTietLayout = new javax.swing.GroupLayout(pnlTaoChiTiet);
        pnlTaoChiTiet.setLayout(pnlTaoChiTietLayout);
        pnlTaoChiTietLayout.setHorizontalGroup(
            pnlTaoChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlTaoChiTietLayout.setVerticalGroup(
            pnlTaoChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaoChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTaoChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 200, 140, -1));

        pnlTblDonHangChuaXacNhan.setBackground(new java.awt.Color(238, 243, 247));
        pnlTblDonHangChuaXacNhan.setForeground(new java.awt.Color(238, 243, 247));

        scpChiTietKhuyenMai.setBackground(new java.awt.Color(238, 243, 247));

        tblChiTietKhuyenMai.setAutoCreateRowSorter(true);
        tblChiTietKhuyenMai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblChiTietKhuyenMai.setFocusable(false);
        tblChiTietKhuyenMai.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblChiTietKhuyenMai.setRowHeight(25);
        tblChiTietKhuyenMai.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblChiTietKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietKhuyenMaiMouseClicked(evt);
            }
        });
        scpChiTietKhuyenMai.setViewportView(tblChiTietKhuyenMai);

        javax.swing.GroupLayout pnlTblDonHangChuaXacNhanLayout = new javax.swing.GroupLayout(pnlTblDonHangChuaXacNhan);
        pnlTblDonHangChuaXacNhan.setLayout(pnlTblDonHangChuaXacNhanLayout);
        pnlTblDonHangChuaXacNhanLayout.setHorizontalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpChiTietKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblDonHangChuaXacNhanLayout.setVerticalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpChiTietKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(pnlTblDonHangChuaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 990, 410));

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblTitleTrangThai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleTrangThai.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleTrangThai.setText("Trạng thái:");
        add(lblTitleTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, 30));

        pnlTrangThai.setBackground(new java.awt.Color(202, 229, 246));

        javax.swing.GroupLayout pnlTrangThaiLayout = new javax.swing.GroupLayout(pnlTrangThai);
        pnlTrangThai.setLayout(pnlTrangThaiLayout);
        pnlTrangThaiLayout.setHorizontalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        pnlTrangThaiLayout.setVerticalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(pnlTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemMaKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemMaKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemMaKhuyenMaiActionPerformed

    private void pnlTaoChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaoChiTietMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new ThemChiTietKhuyenMaiJPanel());
            this.validate();
            this.repaint();
        }        
    }//GEN-LAST:event_pnlTaoChiTietMouseClicked

    private void tblChiTietKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietKhuyenMaiMouseClicked
        int column = tblChiTietKhuyenMai.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblChiTietKhuyenMai.getRowHeight();

        if(row < tblChiTietKhuyenMai.getRowCount() && row >= 0 && column < tblChiTietKhuyenMai.getColumnCount() && column >= 0){
             if (SwingUtilities.isLeftMouseButton(evt)){
                     
            currentChiTietKhuyenMai = quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.getByMaChiTietKhuyenMai(tblChiTietKhuyenMai.getModel().getValueAt(row, 1).toString());
            currentDonHangList = quanlycuahangsach.quanlycuahangsach.DonHangBUS.getDonHangByMaGiamGia(currentChiTietKhuyenMai.getMaCode());
            
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new ThongTinChiTietKhuyenMaiPanel());
            this.validate();
            this.repaint();
             }
        }
    }//GEN-LAST:event_tblChiTietKhuyenMaiMouseClicked

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new KhuyenMaiJPanel());
            this.validate();
            this.repaint();
        }// TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void getAdvancedSearch(){
    HashMap<String, String> advancedSearch = new HashMap<>();
        advancedSearch.put("MaChuongTrinhKhuyenMai",txtTimKiemMaChuongTrinh.getText());
        advancedSearch.put("MaChiTiet",txtTimKiemMaKhuyenMai.getText());
        advancedSearch.put("TrangThai","");
        if(!cbxTrangThai.getSelectedItem().equals("Tất cả"))
            advancedSearch.replace("TrangThai", cbxTrangThai.getSelectedItem().toString());
        
        arraySearch = quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.advancedSearch(advancedSearch);
        search();
    }
    
    private void search(){
       listTableModel.setRowCount(0);
        arraySearch.forEach(ChiTietKhuyenMai ->{
            Vector row = new Vector();
row.add(ChiTietKhuyenMai.getMaChuongTrinhKhuyenMai());
            row.add(ChiTietKhuyenMai.getMaChiTietKhuyenMai());
            row.add(ChiTietKhuyenMai.getMaCode());
            row.add(ChiTietKhuyenMai.getSoLuong());
            row.add(Integer.parseInt(ChiTietKhuyenMai.getSoLuong())-Integer.parseInt(ChiTietKhuyenMai.getSoLuongDaDung()));
            row.add(DateTime.TimestampToDateString(ChiTietKhuyenMai.getThoiGianBatDauSuDung(),0));
            row.add(DateTime.TimestampToDateString(ChiTietKhuyenMai.getThoiGianKetThucSuDung(),0));
                       listTableModel.addRow(row);
        });
        tblChiTietKhuyenMai.setModel(listTableModel);
    
    }
    private void txtTimKiemMaKhuyenMaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaKhuyenMaiKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaKhuyenMaiKeyReleased

    private void txtTimKiemMaChuongTrinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaChuongTrinhKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaChuongTrinhKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMaChiTiet;
    private javax.swing.JLabel lblMaKhuyenMai;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblTaoPhieuNhap;
    private javax.swing.JLabel lblTitleTrangThai;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlTaoChiTiet;
    private GUI.Rounded pnlTblDonHangChuaXacNhan;
    private GUI.Rounded pnlTimKiemMaChuongTrinh;
    private GUI.Rounded pnlTimKiemTenChuongTrinh;
    private javax.swing.JPanel pnlTrangThai;
    private javax.swing.JScrollPane scpChiTietKhuyenMai;
    private static javax.swing.JTable tblChiTietKhuyenMai;
    private javax.swing.JTextField txtTimKiemMaChuongTrinh;
    private javax.swing.JTextField txtTimKiemMaKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
