/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhuyenMai;

import DTO.ChiTietDonHangDTO;
import DTO.KhachHangDTO;
import DTO.SanPhamDTO;
import GUI.DonHang.*;
import GUI.DonHangJPanel;
import GUI.Table.RenderTable;
import static GUI.TongQuanJPanel.customTable;
import static GUI.TongQuanJPanel.setJTableColumnsWidth;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import static quanlycuahangsach.Currency.changeCurrency;
import quanlycuahangsach.DateTime;

/**
 *
 * @author admin
 */
public class ChiTietDonHangTrongChuongTrinhJPanel extends javax.swing.JPanel {
    static KhachHangDTO currentKhachHang;
    static DefaultTableModel listTableModel;
    Object[] columnNames ={"Sản phẩm","Số lượng","Đơn giá","Tạm tính"};
    /**
     * Creates new form SanPhamJPanel
     */
    public void setShadow(){
        pnlThongTin.setShadow(1);
    }    
    public void ShowTable(JTable table,Object[] columnName){
        
        table.setDefaultRenderer(Object.class, new RenderTable());
        
        Object columnNames[] = columnName;
        listTableModel = new DefaultTableModel(columnNames,0);
        fetchAllSanPham();
    }     
    
    public void fetchAllSanPham(){
    listTableModel.setRowCount(0);
        for(int i=0;i<GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentChiTietDonHangList.size();i++){
            Vector row = new Vector();
            SanPhamDTO sanpham = GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentSanPhamList.get(i);
            ChiTietDonHangDTO chitietdonhang = GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentChiTietDonHangList.get(i);
            row.add(sanpham.getTenSanPham());
            row.add(chitietdonhang.getSoLuong());
            row.add(changeCurrency(chitietdonhang.getDonGia()));
            row.add(changeCurrency(""+Double.parseDouble(chitietdonhang.getSoLuong())*Double.parseDouble(chitietdonhang.getDonGia())));
            listTableModel.addRow(row);
        }
        tblSanPham.setModel(listTableModel);
    
    }
    public ChiTietDonHangTrongChuongTrinhJPanel() {
        initComponents();
        customTable(tblSanPham,scpSanPham);
        ShowTable(tblSanPham,columnNames);
        setShadow();
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setData();       
    }
    public void setData(){
        KhachHangDTO KhachHang = quanlycuahangsach.quanlycuahangsach.KhachHangBUS.getByMaKhachHang(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentDonHang.getMaKhachHang());
            lblHoTen.setText(KhachHang.getHoTen());
            lblSoDienThoai.setText(KhachHang.getSoDienThoai());
            lblEmail.setText(KhachHang.getEmail());
            lblDiaChi.setText(KhachHang.getDiaChi());
            lblMaDonHang.setText(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentDonHang.getMaKhachHang());
            lblNgayDat.setText(DateTime.TimestampToDateString(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentDonHang.getNgayXuat(),0));
            lblMaGiamGia.setText(GUI.KhuyenMai.ThongTinChuongTrinhKhuyenMaiJPanel.currentChiTietKhuyenMai.getMaCode());
            lblTamTinh.setText(changeCurrency(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentDonHang.getTamTinh()));
            lblGiamGia.setText(changeCurrency(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentDonHang.getGiamGia()));
            lblPhiVanChuyen.setText(changeCurrency(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentDonHang.getPhiVanChuyen()));
            lblTongTien.setText(changeCurrency(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentDonHang.getTongTien()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTin = new GUI.Rounded();
        scpSanPham = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblThongTinHoaDon1 = new javax.swing.JLabel();
        pnlTongTien = new javax.swing.JPanel();
        lblTitleTamTinh = new javax.swing.JLabel();
        lblTitleMaGiamGia = new javax.swing.JLabel();
        lblTitlePhiVanChuyen = new javax.swing.JLabel();
        lblTitleTong = new javax.swing.JLabel();
        lblTamTinh = new javax.swing.JLabel();
        lblGiamGia = new javax.swing.JLabel();
        lblPhiVanChuyen = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        pnlThongTinHoaDon = new javax.swing.JPanel();
        lblTitleNgayDat = new javax.swing.JLabel();
        lblTitleSoDienThoai = new javax.swing.JLabel();
        lblTitleDiaChi = new javax.swing.JLabel();
        lblTitleEmail = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDiaChi = new javax.swing.JTextArea();
        lblTitleMaGiamGia1 = new javax.swing.JLabel();
        lblNgayDat = new javax.swing.JLabel();
        lblMaGiamGia = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblTitleHoTen = new javax.swing.JLabel();
        lblTitleMaDonHang = new javax.swing.JLabel();
        lblMaDonHang = new javax.swing.JLabel();
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongTin.setBackground(new java.awt.Color(238, 243, 247));
        pnlThongTin.setForeground(new java.awt.Color(238, 243, 247));
        pnlThongTin.setPreferredSize(new java.awt.Dimension(920, 750));
        pnlThongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scpSanPham.setForeground(new java.awt.Color(255, 255, 255));

        tblSanPham.setAutoCreateRowSorter(true);
        tblSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSanPham.setFocusable(false);
        tblSanPham.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSanPham.setRowHeight(25);
        tblSanPham.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        scpSanPham.setViewportView(tblSanPham);

        pnlThongTin.add(scpSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 214, 993, 293));

        lblThongTinHoaDon1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinHoaDon1.setForeground(new java.awt.Color(0, 52, 102));
        lblThongTinHoaDon1.setText("Sản phẩm");
        pnlThongTin.add(lblThongTinHoaDon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 186, -1, -1));

        pnlTongTien.setBackground(new java.awt.Color(255, 255, 255));
        pnlTongTien.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleTamTinh.setBackground(new java.awt.Color(192, 192, 192));
        lblTitleTamTinh.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleTamTinh.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleTamTinh.setText("Tạm tính");

        lblTitleMaGiamGia.setBackground(new java.awt.Color(192, 192, 192));
        lblTitleMaGiamGia.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleMaGiamGia.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleMaGiamGia.setText("Mã giảm giá");

        lblTitlePhiVanChuyen.setBackground(new java.awt.Color(192, 192, 192));
        lblTitlePhiVanChuyen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitlePhiVanChuyen.setForeground(new java.awt.Color(0, 52, 102));
        lblTitlePhiVanChuyen.setText("Phí vận chuyển");

        lblTitleTong.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleTong.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleTong.setText("Tổng");

        lblTamTinh.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblTamTinh.setText("3.600.000đ");

        lblGiamGia.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblGiamGia.setText("3.600.000đ");

        lblPhiVanChuyen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblPhiVanChuyen.setText("3.600.000đ");

        lblTongTien.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(210, 48, 44));
        lblTongTien.setText("3.600.000đ");

        javax.swing.GroupLayout pnlTongTienLayout = new javax.swing.GroupLayout(pnlTongTien);
        pnlTongTien.setLayout(pnlTongTienLayout);
        pnlTongTienLayout.setHorizontalGroup(
            pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongTienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleMaGiamGia)
                    .addComponent(lblTitlePhiVanChuyen)
                    .addComponent(lblTitleTong)
                    .addComponent(lblTitleTamTinh))
                .addGap(48, 48, 48)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTamTinh)
                    .addComponent(lblTongTien)
                    .addComponent(lblGiamGia)
                    .addComponent(lblPhiVanChuyen))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        pnlTongTienLayout.setVerticalGroup(
            pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongTienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleTamTinh)
                    .addComponent(lblTamTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleMaGiamGia)
                    .addComponent(lblGiamGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitlePhiVanChuyen)
                    .addComponent(lblPhiVanChuyen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongTien)
                    .addComponent(lblTitleTong)))
        );

        pnlThongTin.add(pnlTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 513, -1, -1));

        pnlThongTinHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleNgayDat.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleNgayDat.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleNgayDat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleNgayDat.setText("Ngày đặt:");
        pnlThongTinHoaDon.add(lblTitleNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 70, -1));

        lblTitleSoDienThoai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleSoDienThoai.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleSoDienThoai.setText("Số điện thoại:");
        pnlThongTinHoaDon.add(lblTitleSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblTitleDiaChi.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleDiaChi.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleDiaChi.setText("Địa chỉ:");
        pnlThongTinHoaDon.add(lblTitleDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblTitleEmail.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleEmail.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleEmail.setText("Email:");
        pnlThongTinHoaDon.add(lblTitleEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblEmail.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(24, 24, 24));
        lblEmail.setText("abcxyz@gmail.com");
        pnlThongTinHoaDon.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        lblSoDienThoai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(24, 24, 24));
        lblSoDienThoai.setText("0123456789");
        pnlThongTinHoaDon.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(53, 55, 70));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lblDiaChi.setColumns(20);
        lblDiaChi.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(24, 24, 24));
        lblDiaChi.setLineWrap(true);
        lblDiaChi.setRows(5);
        lblDiaChi.setText("120 Công Chúa Ngọc Hân, Phường 12\nQuận 11, TP Hồ Chí Minh\n");
        lblDiaChi.setBorder(null);
        lblDiaChi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblDiaChi.setEnabled(false);
        jScrollPane1.setViewportView(lblDiaChi);

        pnlThongTinHoaDon.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 50));

        lblTitleMaGiamGia1.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleMaGiamGia1.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleMaGiamGia1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaGiamGia1.setText("Mã giảm giá:");
        pnlThongTinHoaDon.add(lblTitleMaGiamGia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 80, -1));

        lblNgayDat.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblNgayDat.setForeground(new java.awt.Color(24, 24, 24));
        lblNgayDat.setText("01/05/2000");
        pnlThongTinHoaDon.add(lblNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        lblMaGiamGia.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblMaGiamGia.setForeground(new java.awt.Color(210, 48, 44));
        lblMaGiamGia.setText("MAGIAMGIA2020");
        pnlThongTinHoaDon.add(lblMaGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        pnlThongTin.add(pnlThongTinHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 987, 124));

        lblHoTen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(24, 24, 24));
        lblHoTen.setText("Phan Công Sơn");
        pnlThongTin.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 30, -1, -1));

        lblTitleHoTen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleHoTen.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleHoTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHoTen.setText("Họ tên:");
        pnlThongTin.add(lblTitleHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 31, 50, -1));

        lblTitleMaDonHang.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 13)); // NOI18N
        lblTitleMaDonHang.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleMaDonHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaDonHang.setText("Mã đơn hàng:");
        pnlThongTin.add(lblTitleMaDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 31, 90, -1));

        lblMaDonHang.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblMaDonHang.setForeground(new java.awt.Color(24, 24, 24));
        lblMaDonHang.setText("12345");
        pnlThongTin.add(lblMaDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        add(pnlThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1010, 610));

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int column = tblSanPham.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblSanPham.getRowHeight();

        if(row < tblSanPham.getRowCount() && row >= 0 && column < tblSanPham.getColumnCount() && column >= 0){

            for(int i=0;i<tblSanPham.getColumnCount()-2;i++){
                System.out.println(tblSanPham.getModel().getValueAt(row,i));
            }

        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
     if (SwingUtilities.isLeftMouseButton(evt)){  
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel());
        this.validate();
        this.repaint();   
     }// TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaDonHang;
    private javax.swing.JLabel lblMaGiamGia;
    private javax.swing.JLabel lblNgayDat;
    private javax.swing.JLabel lblPhiVanChuyen;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTamTinh;
    private javax.swing.JLabel lblThongTinHoaDon1;
    private javax.swing.JLabel lblTitleDiaChi;
    private javax.swing.JLabel lblTitleEmail;
    private javax.swing.JLabel lblTitleHoTen;
    private javax.swing.JLabel lblTitleMaDonHang;
    private javax.swing.JLabel lblTitleMaGiamGia;
    private javax.swing.JLabel lblTitleMaGiamGia1;
    private javax.swing.JLabel lblTitleNgayDat;
    private javax.swing.JLabel lblTitlePhiVanChuyen;
    private javax.swing.JLabel lblTitleSoDienThoai;
    private javax.swing.JLabel lblTitleTamTinh;
    private javax.swing.JLabel lblTitleTong;
    private javax.swing.JLabel lblTongTien;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlThongTin;
    private javax.swing.JPanel pnlThongTinHoaDon;
    private javax.swing.JPanel pnlTongTien;
    private javax.swing.JScrollPane scpSanPham;
    private static javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
