/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhuyenMai;

import DTO.ChiTietKhuyenMaiDTO;
import DTO.ChuongTrinhKhuyenMaiDTO;
import GUI.KhuyenMaiJPanel;
import GUI.Sweet.SweetComboBox;
import GUI.Table.RenderTable;
import static GUI.TongQuanJPanel.customTable;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import quanlycuahangsach.DateTime;

/**
 *
 * @author admin
 */
public class ChuongTrinhKhuyenMaiJPanel extends javax.swing.JPanel {
    static ChuongTrinhKhuyenMaiDTO currentChuongTrinhKhuyenMai;
    static ArrayList<ChiTietKhuyenMaiDTO> currentChiTietKhuyenMaiList;
    static DefaultTableModel listTableModel;
    public ArrayList<ChuongTrinhKhuyenMaiDTO> arraySearch;
    /**
     * Creates new form ChuongTrinhKhuyenMaiJPanel
     */
    Object[] columnNames ={"Mã CT khuyến mãi ","Tên CT khuyến mãi","Ngày tạo","Số lượng chi tiết khuyến mãi"};
    /**
     * Creates new form ChuongTrinhKhuyenMaiJPanel
     */
 
    public void setShadow(){
        pnlTblDonHangChuaXacNhan.setShadow(1);
    }     
    public void ShowTable(JTable table,Object[] columnName){
        table.setDefaultRenderer(Object.class, new RenderTable());
        listTableModel = new DefaultTableModel(columnNames,0);
        fetchAll();
    }
    public static void fetchAll(){
        listTableModel.setRowCount(0);
        quanlycuahangsach.quanlycuahangsach.ChuongTrinhKhuyenMaiBUS.ChuongTrinhKhuyenMaiList.forEach(ChuongTrinhKhuyenMai ->{
            Vector row = new Vector();
            row.add(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai());
            row.add(ChuongTrinhKhuyenMai.getTenChuongTrinh());
            row.add(DateTime.TimestampToDateString(ChuongTrinhKhuyenMai.getNgayTao(),0));
            row.add(quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.getSoLuongChiTietKhuyenMai(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai())); //COUNT(*) CHITIETKHUYENMAI
           
            listTableModel.addRow(row);
        });
        tblChuongTrinhKhuyenMai.setModel(listTableModel);
    
    }
    public ChuongTrinhKhuyenMaiJPanel() {
        initComponents();
        customTable(tblChuongTrinhKhuyenMai,scpDonHang);
        ShowTable(tblChuongTrinhKhuyenMai,columnNames);
        pnlTaoChuongTrinh.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
   
        setShadow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlTimKiemTenChuongTrinh = new GUI.Rounded();
        txtTimKiemTenChuongTrinh = new javax.swing.JTextField();
        pnlTimKiemMaChuongTrinh = new GUI.Rounded();
        txtTimKiemMaChuongTrinh = new javax.swing.JTextField();
        pnlTaoChuongTrinh = new GUI.Rounded();
        lblTaoPhieuNhap = new javax.swing.JLabel();
        pnlTblDonHangChuaXacNhan = new GUI.Rounded();
        scpDonHang = new javax.swing.JScrollPane();
        tblChuongTrinhKhuyenMai = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 52, 102));
        jLabel3.setText("Mã chương trình:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jLabel1.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 52, 102));
        jLabel1.setText("Tên chương trình:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        pnlTimKiemTenChuongTrinh.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemTenChuongTrinh.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemTenChuongTrinh.setFocusable(false);

        txtTimKiemTenChuongTrinh.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemTenChuongTrinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemTenChuongTrinh.setBorder(null);
        txtTimKiemTenChuongTrinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemTenChuongTrinhKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemTenChuongTrinhLayout = new javax.swing.GroupLayout(pnlTimKiemTenChuongTrinh);
        pnlTimKiemTenChuongTrinh.setLayout(pnlTimKiemTenChuongTrinhLayout);
        pnlTimKiemTenChuongTrinhLayout.setHorizontalGroup(
            pnlTimKiemTenChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemTenChuongTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemTenChuongTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );
        pnlTimKiemTenChuongTrinhLayout.setVerticalGroup(
            pnlTimKiemTenChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemTenChuongTrinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemTenChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemTenChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 470, -1));

        pnlTimKiemMaChuongTrinh.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemMaChuongTrinh.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemMaChuongTrinh.setFocusable(false);

        txtTimKiemMaChuongTrinh.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemMaChuongTrinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaChuongTrinh.setBorder(null);
        txtTimKiemMaChuongTrinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaChuongTrinhKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemMaChuongTrinhLayout = new javax.swing.GroupLayout(pnlTimKiemMaChuongTrinh);
        pnlTimKiemMaChuongTrinh.setLayout(pnlTimKiemMaChuongTrinhLayout);
        pnlTimKiemMaChuongTrinhLayout.setHorizontalGroup(
            pnlTimKiemMaChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemMaChuongTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlTimKiemMaChuongTrinhLayout.setVerticalGroup(
            pnlTimKiemMaChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemMaChuongTrinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemMaChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 470, -1));

        pnlTaoChuongTrinh.setBackground(new java.awt.Color(238, 243, 247));
        pnlTaoChuongTrinh.setForeground(new java.awt.Color(0, 146, 242));
        pnlTaoChuongTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaoChuongTrinhMouseClicked(evt);
            }
        });

        lblTaoPhieuNhap.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTaoPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTaoPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaoPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        lblTaoPhieuNhap.setText("Tạo chương trình");

        javax.swing.GroupLayout pnlTaoChuongTrinhLayout = new javax.swing.GroupLayout(pnlTaoChuongTrinh);
        pnlTaoChuongTrinh.setLayout(pnlTaoChuongTrinhLayout);
        pnlTaoChuongTrinhLayout.setHorizontalGroup(
            pnlTaoChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoChuongTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTaoChuongTrinhLayout.setVerticalGroup(
            pnlTaoChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaoChuongTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTaoChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));

        pnlTblDonHangChuaXacNhan.setBackground(new java.awt.Color(238, 243, 247));
        pnlTblDonHangChuaXacNhan.setForeground(new java.awt.Color(238, 243, 247));

        scpDonHang.setBackground(new java.awt.Color(238, 243, 247));

        tblChuongTrinhKhuyenMai.setAutoCreateRowSorter(true);
        tblChuongTrinhKhuyenMai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblChuongTrinhKhuyenMai.setFocusable(false);
        tblChuongTrinhKhuyenMai.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblChuongTrinhKhuyenMai.setRowHeight(25);
        tblChuongTrinhKhuyenMai.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblChuongTrinhKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChuongTrinhKhuyenMaiMouseClicked(evt);
            }
        });
        scpDonHang.setViewportView(tblChuongTrinhKhuyenMai);

        javax.swing.GroupLayout pnlTblDonHangChuaXacNhanLayout = new javax.swing.GroupLayout(pnlTblDonHangChuaXacNhan);
        pnlTblDonHangChuaXacNhan.setLayout(pnlTblDonHangChuaXacNhanLayout);
        pnlTblDonHangChuaXacNhanLayout.setHorizontalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblDonHangChuaXacNhanLayout.setVerticalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(pnlTblDonHangChuaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 990, 410));

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTaoChuongTrinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaoChuongTrinhMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt))
        new TaoChuongTrinhJFrame().setVisible(true);
    }//GEN-LAST:event_pnlTaoChuongTrinhMouseClicked

    private void tblChuongTrinhKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuongTrinhKhuyenMaiMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){ 
        int column = tblChuongTrinhKhuyenMai.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblChuongTrinhKhuyenMai.getRowHeight();

        if(row < tblChuongTrinhKhuyenMai.getRowCount() && row >= 0 && column < tblChuongTrinhKhuyenMai.getColumnCount() && column >= 0){
            currentChuongTrinhKhuyenMai = quanlycuahangsach.quanlycuahangsach.ChuongTrinhKhuyenMaiBUS.getByMaChuongTrinhKhuyenMai(tblChuongTrinhKhuyenMai.getModel().getValueAt(row, 0).toString());
            currentChiTietKhuyenMaiList = quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.getChiTietKhuyenMaiByMaChuongTrinhKhuyenMai(currentChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai());
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new ThongTinChuongTrinhKhuyenMaiJPanel());
            this.validate();
            this.repaint();
        }
        }
    }//GEN-LAST:event_tblChuongTrinhKhuyenMaiMouseClicked

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new KhuyenMaiJPanel());
            this.validate();
            this.repaint();
        }// TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    public void getAdvancedSearch(){
        HashMap<String, String> advancedSearch = new HashMap<>();
        advancedSearch.put("MaChuongTrinhKhuyenMai",txtTimKiemMaChuongTrinh.getText());
        advancedSearch.put("TenChuongTrinhKhuyenMai",txtTimKiemTenChuongTrinh.getText());
        arraySearch = quanlycuahangsach.quanlycuahangsach.ChuongTrinhKhuyenMaiBUS.advancedSearch(advancedSearch);
        search();
    }
    
    private void search(){
        listTableModel.setRowCount(0);
        arraySearch.forEach(ChuongTrinhKhuyenMai ->{
            Vector row = new Vector();
row.add(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai());
            row.add(ChuongTrinhKhuyenMai.getTenChuongTrinh());
            row.add(DateTime.TimestampToDateString(ChuongTrinhKhuyenMai.getNgayTao(),0));
            row.add(quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.getSoLuongChiTietKhuyenMai(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai())); //COUNT(*) CHITIETKHUYENMAI
           
                       listTableModel.addRow(row);
        });
        tblChuongTrinhKhuyenMai.setModel(listTableModel);
    
    }
    private void txtTimKiemMaChuongTrinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaChuongTrinhKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaChuongTrinhKeyReleased

    private void txtTimKiemTenChuongTrinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemTenChuongTrinhKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemTenChuongTrinhKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblTaoPhieuNhap;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlTaoChuongTrinh;
    private GUI.Rounded pnlTblDonHangChuaXacNhan;
    private GUI.Rounded pnlTimKiemMaChuongTrinh;
    private GUI.Rounded pnlTimKiemTenChuongTrinh;
    private javax.swing.JScrollPane scpDonHang;
    private static javax.swing.JTable tblChuongTrinhKhuyenMai;
    private javax.swing.JTextField txtTimKiemMaChuongTrinh;
    private javax.swing.JTextField txtTimKiemTenChuongTrinh;
    // End of variables declaration//GEN-END:variables
}
