/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhuyenMai;

import DTO.ChiTietKhuyenMaiDTO;
import DTO.DonHangDTO;
import GUI.KhuyenMaiJPanel;
import GUI.Table.RenderTable;
import static GUI.TongQuanJPanel.customTable;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import quanlycuahangsach.DateTime;

/**
 *
 * @author admin
 */
public class ThongTinChuongTrinhKhuyenMaiJPanel extends javax.swing.JPanel {

    static DefaultTableModel listTableModel;
    Object[] columnNames = {"Mã CT khuyến mãi", "Mã code", "Số lượng", "% khuyến mãi", "Giá tiền khuyến mãi", "Ngày bắt đầu","Ngày kết thúc"};
    static ChiTietKhuyenMaiDTO currentChiTietKhuyenMai;
    static ArrayList<DonHangDTO> currentDonHangList;
    /**
     * Creates new form ThongTinChuongTrinhKhuyenMai
     */
    public void setShadow() {
        pnlTblDonHangChuaXacNhan.setShadow(1);
    }

    public void ShowTable(JTable table, Object[] columnName) {
        table.setDefaultRenderer(Object.class, new RenderTable());
         listTableModel = new DefaultTableModel(columnNames,0);
        
        fetchAllChiTietKhuyenMai();
    }

    public ThongTinChuongTrinhKhuyenMaiJPanel() {
        initComponents();
        customTable(tblThongTinChuongTrinh, scpThongTinChuongTrinh);
        ShowTable(tblThongTinChuongTrinh, columnNames);
        setShadow();
        setData();
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    public void setData() {
        lblMaChuongTrinhKhuyenMai.setText(GUI.KhuyenMai.ChuongTrinhKhuyenMaiJPanel.currentChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai());
        lblTenChuongTrinhKhuyenMai.setText(GUI.KhuyenMai.ChuongTrinhKhuyenMaiJPanel.currentChuongTrinhKhuyenMai.getTenChuongTrinh());
        lblSoLuong.setText(quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.getSoLuongChiTietKhuyenMai(GUI.KhuyenMai.ChuongTrinhKhuyenMaiJPanel.currentChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai()));
        lblThoiGianTao.setText(DateTime.TimestampToDateString(GUI.KhuyenMai.ChuongTrinhKhuyenMaiJPanel.currentChuongTrinhKhuyenMai.getNgayTao(), 0));
    }

    public void fetchAllChiTietKhuyenMai() {
        listTableModel.setRowCount(0);
        GUI.KhuyenMai.ChuongTrinhKhuyenMaiJPanel.currentChiTietKhuyenMaiList.forEach(ChiTietKhuyenMai -> {
            Vector row = new Vector();
            row.add(ChiTietKhuyenMai.getMaChiTietKhuyenMai());
            row.add(ChiTietKhuyenMai.getMaCode());
            row.add(ChiTietKhuyenMai.getSoLuong());
            row.add(ChiTietKhuyenMai.getPhanTramKhuyenMai());
            row.add(ChiTietKhuyenMai.getGiaTienKhuyenMai());
            row.add(DateTime.TimestampToDateString(ChiTietKhuyenMai.getThoiGianBatDauSuDung(),0));
            row.add(DateTime.TimestampToDateString(ChiTietKhuyenMai.getThoiGianKetThucSuDung(),0));
            listTableModel.addRow(row);
        });
        tblThongTinChuongTrinh.setModel(listTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTblDonHangChuaXacNhan = new GUI.Rounded();
        scpThongTinChuongTrinh = new javax.swing.JScrollPane();
        tblThongTinChuongTrinh = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblThongTinMaKhuyenMai2 = new javax.swing.JLabel();
        lblTitleMaChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblTitleTenChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblTitleSoLuong = new javax.swing.JLabel();
        lblTitleThoiGianTao = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblThoiGianTao = new javax.swing.JLabel();
        lblTenChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblMaChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblDonHang = new javax.swing.JLabel();
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTblDonHangChuaXacNhan.setBackground(new java.awt.Color(238, 243, 247));
        pnlTblDonHangChuaXacNhan.setForeground(new java.awt.Color(238, 243, 247));
        pnlTblDonHangChuaXacNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scpThongTinChuongTrinh.setBackground(new java.awt.Color(238, 243, 247));

        tblThongTinChuongTrinh.setAutoCreateRowSorter(true);
        tblThongTinChuongTrinh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblThongTinChuongTrinh.setFocusable(false);
        tblThongTinChuongTrinh.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblThongTinChuongTrinh.setRowHeight(25);
        tblThongTinChuongTrinh.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblThongTinChuongTrinh.setShowGrid(false);
        tblThongTinChuongTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinChuongTrinhMouseClicked(evt);
            }
        });
        scpThongTinChuongTrinh.setViewportView(tblThongTinChuongTrinh);

        pnlTblDonHangChuaXacNhan.add(scpThongTinChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 978, 312));

        lblThongTinMaKhuyenMai2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinMaKhuyenMai2.setForeground(new java.awt.Color(0, 146, 242));
        lblThongTinMaKhuyenMai2.setText("Thông tin chương trình khuyến mãi");
        pnlTblDonHangChuaXacNhan.add(lblThongTinMaKhuyenMai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTitleMaChuongTrinhKhuyenMai.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleMaChuongTrinhKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaChuongTrinhKhuyenMai.setText("Mã chương trình khuyến mãi:");
        pnlTblDonHangChuaXacNhan.add(lblTitleMaChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, -1));

        lblTitleTenChuongTrinhKhuyenMai.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleTenChuongTrinhKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleTenChuongTrinhKhuyenMai.setText("Tên chương trình:");
        pnlTblDonHangChuaXacNhan.add(lblTitleTenChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 190, 30));

        lblTitleSoLuong.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleSoLuong.setText("Số lượng chi tiết khuyến mãi:");
        pnlTblDonHangChuaXacNhan.add(lblTitleSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblTitleThoiGianTao.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleThoiGianTao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleThoiGianTao.setText("Thời gian tạo:");
        pnlTblDonHangChuaXacNhan.add(lblTitleThoiGianTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblSoLuong.setText("500");
        pnlTblDonHangChuaXacNhan.add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        lblThoiGianTao.setText("01/05/2000");
        pnlTblDonHangChuaXacNhan.add(lblThoiGianTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        lblTenChuongTrinhKhuyenMai.setText("Tên chương trình");
        pnlTblDonHangChuaXacNhan.add(lblTenChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        lblMaChuongTrinhKhuyenMai.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblMaChuongTrinhKhuyenMai.setForeground(new java.awt.Color(0, 146, 242));
        lblMaChuongTrinhKhuyenMai.setText("#CT123");
        pnlTblDonHangChuaXacNhan.add(lblMaChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        lblDonHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDonHang.setForeground(new java.awt.Color(0, 146, 242));
        lblDonHang.setText("Chi tiết khuyến mãi");
        pnlTblDonHangChuaXacNhan.add(lblDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        add(pnlTblDonHangChuaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 990, 600));

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblThongTinChuongTrinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinChuongTrinhMouseClicked
        int column = tblThongTinChuongTrinh.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblThongTinChuongTrinh.getRowHeight();

        if (row < tblThongTinChuongTrinh.getRowCount() && row >= 0 && column < tblThongTinChuongTrinh.getColumnCount() && column >= 0) {
            currentChiTietKhuyenMai = quanlycuahangsach.quanlycuahangsach.ChiTietKhuyenMaiBUS.getByMaChiTietKhuyenMai(tblThongTinChuongTrinh.getModel().getValueAt(row, 0).toString());
            currentDonHangList = quanlycuahangsach.quanlycuahangsach.DonHangBUS.getDonHangByMaGiamGia(currentChiTietKhuyenMai.getMaCode());
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel());
            this.validate();
            this.repaint();
        }
    }//GEN-LAST:event_tblThongTinChuongTrinhMouseClicked

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new ChuongTrinhKhuyenMaiJPanel());
            this.validate();
            this.repaint();
        }// TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDonHang;
    private javax.swing.JLabel lblMaChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblThoiGianTao;
    private javax.swing.JLabel lblThongTinMaKhuyenMai2;
    private javax.swing.JLabel lblTitleMaChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblTitleSoLuong;
    private javax.swing.JLabel lblTitleTenChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblTitleThoiGianTao;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlTblDonHangChuaXacNhan;
    private javax.swing.JScrollPane scpThongTinChuongTrinh;
    private javax.swing.JTable tblThongTinChuongTrinh;
    // End of variables declaration//GEN-END:variables
}
