/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhuyenMai;

import DTO.SanPhamDTO;
import GUI.Sweet.SweetComboBox;
import GUI.Table.RenderTable;
import static GUI.TongQuanJPanel.customTable;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import static quanlycuahangsach.unicode.removeAccent;

/**
 *
 * @author admin
 */
public class XemSanPhamTrongChuongTrinhKhuyenMaiJPanel extends javax.swing.JFrame {
    SweetComboBox  cbxTacGia,cbxTheLoai,cbxNhaXuatBan;
    static DefaultTableModel listTableModel;
    int xMouse, yMouse;
    Object[] columnNames = {"Mã sản phẩm", "Tên sản phẩm", "Tác giả", "Thể loại", "Nhà xuất bản"};
    ArrayList<SanPhamDTO> arraySearch;
    /**
     * Creates new form XemSanPhamKhuyenMaiJFrame
     */
    public void setComboBox() {
        String[] theloai = quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.getTenTheLoai();
        cbxTheLoai = new SweetComboBox("#CAE5F6", "#181818", 0, 0, 150, 30, theloai);
        pnlTheLoai.add(cbxTheLoai);
        String[] tacgia = quanlycuahangsach.quanlycuahangsach.TacGiaBUS.getTenTacGia();
        cbxTacGia = new SweetComboBox("#CAE5F6", "#181818", 0, 0, 150, 30, tacgia);
        pnlTacGia.add(cbxTacGia);
        String[] nhaxuatban = quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getTenNhaXuatBan();
        cbxNhaXuatBan = new SweetComboBox("#CAE5F6", "#181818", 0, 0, 150, 30, nhaxuatban);
        pnlNhaXuatBan.add(cbxNhaXuatBan);
        cbxNhaXuatBan.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent ie){
                getAdvancedSearch();
            }
        });
        cbxTacGia.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent ie){
                getAdvancedSearch();
            }
        });
        cbxTheLoai.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent ie){
                getAdvancedSearch();
            }
        });
    }

    public void ShowTable(JTable table, Object[] columnName) {

        table.setDefaultRenderer(Object.class, new RenderTable());

        listTableModel = new DefaultTableModel(columnNames, 0);
        fetchAllSanPhamKhuyenMai();
    }

    public static void fetchAllSanPhamKhuyenMai() {
        listTableModel.setRowCount(0);
        if(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentSanPhamKhuyenMaiList == null){
            quanlycuahangsach.quanlycuahangsach.SachBUS.SachList.forEach(SanPham->{
            Vector row = new Vector();
            row.add(SanPham.getMaSanPham());
            row.add(SanPham.getTenSanPham());
            row.add(quanlycuahangsach.quanlycuahangsach.TacGiaBUS.getTenByMa(SanPham.getMaTacGia()));
            row.add(quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.getTenByMa(SanPham.getMaTheLoai()));
            row.add(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getTenByMa(SanPham.getMaNhaXuatBan()));
            listTableModel.addRow(row);
            });
        
        }
        else{
        GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentSanPhamKhuyenMaiList.forEach(SanPhamKhuyenMai -> {
            Vector row = new Vector();
            SanPhamDTO SanPham = quanlycuahangsach.quanlycuahangsach.SachBUS.getByMaSanPham(SanPhamKhuyenMai.getMaSanPham());
            row.add(SanPham.getMaSanPham());
            row.add(SanPham.getTenSanPham());

            row.add(quanlycuahangsach.quanlycuahangsach.TacGiaBUS.getTenByMa(SanPham.getMaTacGia()));
            row.add(quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.getTenByMa(SanPham.getMaTheLoai()));
            row.add(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getTenByMa(SanPham.getMaNhaXuatBan()));
            listTableModel.addRow(row);
        });
        }
        tblSanPham.setModel(listTableModel);

    }

    public XemSanPhamTrongChuongTrinhKhuyenMaiJPanel() {
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(false);
        initComponents();
        customTable(tblSanPham, scpSanPham);
        ShowTable(tblSanPham, columnNames);
        setComboBox();
        setLocationRelativeTo(null);
        lblEdit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlThongTin = new GUI.Rounded();
        scpSanPham = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblDonHang = new javax.swing.JLabel();
        pnlTimKiem = new GUI.Rounded();
        txtTimKiemTenSanPham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        pnlTheLoai = new javax.swing.JPanel();
        pnlTacGia = new javax.swing.JPanel();
        pnlNhaXuatBan = new javax.swing.JPanel();
        pnlTimKiemMaSanPham = new GUI.Rounded();
        txtTimKiemMaSanPham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTin.setForeground(new java.awt.Color(255, 255, 255));
        pnlThongTin.setPreferredSize(new java.awt.Dimension(920, 750));

        scpSanPham.setForeground(new java.awt.Color(255, 255, 255));

        tblSanPham.setAutoCreateRowSorter(true);
        tblSanPham.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSanPham.setFocusable(false);
        tblSanPham.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSanPham.setRowHeight(25);
        tblSanPham.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        scpSanPham.setViewportView(tblSanPham);

        lblDonHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDonHang.setForeground(new java.awt.Color(0, 146, 242));
        lblDonHang.setText("Sản phẩm được phép dùng mã");

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDonHang)
                .addContainerGap(611, Short.MAX_VALUE))
            .addComponent(scpSanPham)
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDonHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(pnlThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 158, 890, 560));

        pnlTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnlTimKiem.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiem.setFocusable(false);

        txtTimKiemTenSanPham.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemTenSanPham.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemTenSanPham.setBorder(null);
        txtTimKiemTenSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemTenSanPhamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemLayout = new javax.swing.GroupLayout(pnlTimKiem);
        pnlTimKiem.setLayout(pnlTimKiemLayout);
        pnlTimKiemLayout.setHorizontalGroup(
            pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlTimKiemLayout.setVerticalGroup(
            pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pnlTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 52, 102));
        jLabel1.setText("Tên sản phẩm:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        lblEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });
        jPanel1.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 60, -1));

        pnlTheLoai.setBackground(new java.awt.Color(202, 229, 246));
        pnlTheLoai.setPreferredSize(new java.awt.Dimension(170, 30));

        javax.swing.GroupLayout pnlTheLoaiLayout = new javax.swing.GroupLayout(pnlTheLoai);
        pnlTheLoai.setLayout(pnlTheLoaiLayout);
        pnlTheLoaiLayout.setHorizontalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlTheLoaiLayout.setVerticalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnlTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, 30));

        pnlTacGia.setBackground(new java.awt.Color(202, 229, 246));
        pnlTacGia.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout pnlTacGiaLayout = new javax.swing.GroupLayout(pnlTacGia);
        pnlTacGia.setLayout(pnlTacGiaLayout);
        pnlTacGiaLayout.setHorizontalGroup(
            pnlTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlTacGiaLayout.setVerticalGroup(
            pnlTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnlTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 150, -1));

        pnlNhaXuatBan.setBackground(new java.awt.Color(202, 229, 246));
        pnlNhaXuatBan.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout pnlNhaXuatBanLayout = new javax.swing.GroupLayout(pnlNhaXuatBan);
        pnlNhaXuatBan.setLayout(pnlNhaXuatBanLayout);
        pnlNhaXuatBanLayout.setHorizontalGroup(
            pnlNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlNhaXuatBanLayout.setVerticalGroup(
            pnlNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnlNhaXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 150, -1));

        pnlTimKiemMaSanPham.setBackground(new java.awt.Color(255, 255, 255));
        pnlTimKiemMaSanPham.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemMaSanPham.setFocusable(false);

        txtTimKiemMaSanPham.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemMaSanPham.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaSanPham.setBorder(null);
        txtTimKiemMaSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaSanPhamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemMaSanPhamLayout = new javax.swing.GroupLayout(pnlTimKiemMaSanPham);
        pnlTimKiemMaSanPham.setLayout(pnlTimKiemMaSanPhamLayout);
        pnlTimKiemMaSanPhamLayout.setHorizontalGroup(
            pnlTimKiemMaSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemMaSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemMaSanPhamLayout.setVerticalGroup(
            pnlTimKiemMaSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemMaSanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pnlTimKiemMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 390, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 52, 102));
        jLabel3.setText("Mã sản phẩm:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 30));

        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int column = tblSanPham.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblSanPham.getRowHeight();

        if (row < tblSanPham.getRowCount() && row >= 0 && column < tblSanPham.getColumnCount() && column >= 0) {

            for (int i = 0; i < tblSanPham.getColumnCount() - 1; i++) {
                System.out.println(tblSanPham.getModel().getValueAt(row, i));
            }

        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_lblEditMouseClicked

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void txtTimKiemTenSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemTenSanPhamKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemTenSanPhamKeyReleased

    private void txtTimKiemMaSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaSanPhamKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaSanPhamKeyReleased
    
    public void search(){
        listTableModel.setRowCount(0);
        arraySearch.forEach(SanPham->{
            Vector row = new Vector();
            row.add(SanPham.getMaSanPham());
            row.add(SanPham.getTenSanPham());
            row.add(quanlycuahangsach.quanlycuahangsach.TacGiaBUS.getTenByMa(SanPham.getMaTacGia()));
            row.add(quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.getTenByMa(SanPham.getMaTheLoai()));
            row.add(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getTenByMa(SanPham.getMaNhaXuatBan()));
            listTableModel.addRow(row);
        });
        tblSanPham.setModel(listTableModel);
    }
    public void getAdvancedSearch(){
           arraySearch = new ArrayList<>();
        if(GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentSanPhamKhuyenMaiList == null){
            quanlycuahangsach.quanlycuahangsach.SachBUS.SachList.forEach(SanPham->{
                boolean TenTacGia = cbxTacGia.getSelectedItem().toString().equals("Tác giả");
                boolean TenTheLoai = cbxTheLoai.getSelectedItem().toString().equals("Thể loại");
                boolean TenNhaXuatBan = cbxNhaXuatBan.getSelectedItem().toString().equals("Nhà xuất bản");
                        if(TenTacGia == false)
                            TenTacGia = SanPham.getMaTacGia().equals(quanlycuahangsach.quanlycuahangsach.TacGiaBUS.getMaByName(cbxTacGia.getSelectedItem().toString()));
                        if(TenTheLoai == false)
                            TenTheLoai = SanPham.getMaTheLoai().equals(quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.getMaByName(cbxTheLoai.getSelectedItem().toString()));
                        if(TenNhaXuatBan == false)
                            TenNhaXuatBan = SanPham.getMaNhaXuatBan().equals(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getMaByName(cbxNhaXuatBan.getSelectedItem().toString()));
                        
                        if(removeAccent(SanPham.getTenSanPham().toLowerCase()).contains(removeAccent(txtTimKiemTenSanPham.getText().toLowerCase())) &&
                        SanPham.getMaSanPham().contains(txtTimKiemMaSanPham.getText().toUpperCase()) &&
                        TenTacGia && TenNhaXuatBan && TenTheLoai)
                    arraySearch.add(SanPham);
            });
        }
        else{
            GUI.KhuyenMai.ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel.currentSanPhamKhuyenMaiList.forEach(SanPhamKhuyenMai -> {
            Vector row = new Vector();
            SanPhamDTO SanPham = quanlycuahangsach.quanlycuahangsach.SachBUS.getByMaSanPham(SanPhamKhuyenMai.getMaSanPham());
            boolean TenTacGia = cbxTacGia.getSelectedItem().toString().equals("Tác giả");
                boolean TenTheLoai = cbxTheLoai.getSelectedItem().toString().equals("Thể loại");
                boolean TenNhaXuatBan = cbxNhaXuatBan.getSelectedItem().toString().equals("Nhà xuất bản");
                        if(TenTacGia == false)
                            TenTacGia = SanPham.getMaTacGia().equals(quanlycuahangsach.quanlycuahangsach.TacGiaBUS.getMaByName(cbxTacGia.getSelectedItem().toString()));
                        if(TenTheLoai == false)
                            TenTheLoai = SanPham.getMaTheLoai().equals(quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.getMaByName(cbxTheLoai.getSelectedItem().toString()));
                        if(TenNhaXuatBan == false)
                            TenNhaXuatBan = SanPham.getMaNhaXuatBan().equals(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getMaByName(cbxNhaXuatBan.getSelectedItem().toString()));
                        
                        if(removeAccent(SanPham.getTenSanPham().toLowerCase()).contains(removeAccent(txtTimKiemTenSanPham.getText().toLowerCase())) &&
                        SanPham.getMaSanPham().contains(txtTimKiemMaSanPham.getText().toUpperCase()) &&
                        TenTacGia && TenNhaXuatBan && TenTheLoai)
                    arraySearch.add(SanPham);
            });
        }
      
        
        
            search();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDonHang;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JPanel pnlNhaXuatBan;
    private javax.swing.JPanel pnlTacGia;
    private javax.swing.JPanel pnlTheLoai;
    private GUI.Rounded pnlThongTin;
    private GUI.Rounded pnlTimKiem;
    private GUI.Rounded pnlTimKiemMaSanPham;
    private javax.swing.JScrollPane scpSanPham;
    private static javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtTimKiemMaSanPham;
    private javax.swing.JTextField txtTimKiemTenSanPham;
    // End of variables declaration//GEN-END:variables
}
