/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author admin
 */
public class DoiMatKhauJFrame extends javax.swing.JFrame {
    int xMouse,yMouse;
    String MaNhanVien;
    /**
     * Creates new form DoiMatKhauJFrame
     */
    public DoiMatKhauJFrame(){
        
    }
    public DoiMatKhauJFrame(String MaNhanVien) {
        this.MaNhanVien = MaNhanVien;
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(false);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        pnlThayDoi.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlHuyBo.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    private void changePass(String OldPass,String NewPassword){
            String result = quanlycuahangsach.quanlycuahangsach.AccountBUS.changePassword(this.MaNhanVien,OldPass,NewPassword);
            if(result.contains("Mật khẩu không khớp")){
                GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Lỗi","Mật khẩu không khớp", 0); 
            }
            else{
            GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Thành công","Đổi mật khẩu thành công", 0); 
            ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(true);
            this.dispose();
            }
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinHoaDon = new javax.swing.JPanel();
        lblTenNhaCungCap = new javax.swing.JLabel();
        lblTitleDiaChi = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        pnlThayDoi = new GUI.Rounded();
        lblThem = new javax.swing.JLabel();
        lblTitleChinhSua = new javax.swing.JLabel();
        pnlHuyBo = new GUI.Rounded();
        lblThem1 = new javax.swing.JLabel();
        txtNhapLaiMatKhau = new javax.swing.JPasswordField();
        txtMatKhauCu = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        pnlThongTinHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenNhaCungCap.setForeground(new java.awt.Color(0, 52, 102));
        lblTenNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenNhaCungCap.setText("Mật khẩu cũ:");
        pnlThongTinHoaDon.add(lblTenNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblTitleDiaChi.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleDiaChi.setText("Nhập lại mật khẩu mới:");
        pnlThongTinHoaDon.add(lblTitleDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblSoDienThoai.setForeground(new java.awt.Color(0, 52, 102));
        lblSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSoDienThoai.setText("Mật khẩu mới:");
        pnlThongTinHoaDon.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        pnlThayDoi.setBackground(new java.awt.Color(255, 255, 255));
        pnlThayDoi.setForeground(new java.awt.Color(37, 213, 54));
        pnlThayDoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThayDoiMouseClicked(evt);
            }
        });

        lblThem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("Thay đổi");

        javax.swing.GroupLayout pnlThayDoiLayout = new javax.swing.GroupLayout(pnlThayDoi);
        pnlThayDoi.setLayout(pnlThayDoiLayout);
        pnlThayDoiLayout.setHorizontalGroup(
            pnlThayDoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThayDoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThem, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlThayDoiLayout.setVerticalGroup(
            pnlThayDoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlThongTinHoaDon.add(pnlThayDoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 90, 40));

        lblTitleChinhSua.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTitleChinhSua.setForeground(new java.awt.Color(0, 146, 242));
        lblTitleChinhSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleChinhSua.setText("Thay đổi mật khẩu");
        pnlThongTinHoaDon.add(lblTitleChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 30));

        pnlHuyBo.setBackground(new java.awt.Color(255, 255, 255));
        pnlHuyBo.setForeground(new java.awt.Color(210, 48, 44));
        pnlHuyBo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHuyBoMouseClicked(evt);
            }
        });

        lblThem1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblThem1.setForeground(new java.awt.Color(255, 255, 255));
        lblThem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem1.setText("Hủy bỏ");

        javax.swing.GroupLayout pnlHuyBoLayout = new javax.swing.GroupLayout(pnlHuyBo);
        pnlHuyBo.setLayout(pnlHuyBoLayout);
        pnlHuyBoLayout.setHorizontalGroup(
            pnlHuyBoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuyBoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThem1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHuyBoLayout.setVerticalGroup(
            pnlHuyBoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlThongTinHoaDon.add(pnlHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtNhapLaiMatKhau.setBackground(new java.awt.Color(202, 229, 246));
        txtNhapLaiMatKhau.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Extra", 0, 14)); // NOI18N
        txtNhapLaiMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtNhapLaiMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhapLaiMatKhauKeyPressed(evt);
            }
        });
        pnlThongTinHoaDon.add(txtNhapLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 100, 30));

        txtMatKhauCu.setBackground(new java.awt.Color(202, 229, 246));
        txtMatKhauCu.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Extra", 0, 14)); // NOI18N
        txtMatKhauCu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMatKhauCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauCuKeyPressed(evt);
            }
        });
        pnlThongTinHoaDon.add(txtMatKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 210, 30));

        txtMatKhauMoi.setBackground(new java.awt.Color(202, 229, 246));
        txtMatKhauMoi.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Extra", 0, 14)); // NOI18N
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMatKhauMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauMoiKeyPressed(evt);
            }
        });
        pnlThongTinHoaDon.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void validation(){
         if(txtNhapLaiMatKhau.getText().isEmpty() || txtMatKhauMoi.getText().isEmpty()){
            GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Lỗi","Không được bỏ trống", 0);
        } 
        else if(!txtNhapLaiMatKhau.getText().equals(txtMatKhauMoi.getText())){
            GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Lỗi","Mật khẩu nhập lại không khớp", 0);
        } 
        else 
            changePass(txtMatKhauCu.getText(),txtMatKhauMoi.getText());   
}
    private void pnlThayDoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThayDoiMouseClicked
        if(SwingUtilities.isLeftMouseButton(evt)){
            validation();

        }
    }//GEN-LAST:event_pnlThayDoiMouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y-yMouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void pnlHuyBoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyBoMouseClicked
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_pnlHuyBoMouseClicked

    private void txtNhapLaiMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhapLaiMatKhauKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            validation();

    }//GEN-LAST:event_txtNhapLaiMatKhauKeyPressed

    private void txtMatKhauCuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauCuKeyPressed
     if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         txtMatKhauMoi.requestFocus();
    }//GEN-LAST:event_txtMatKhauCuKeyPressed

    private void txtMatKhauMoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauMoiKeyPressed
     if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         txtNhapLaiMatKhau.requestFocus();
    }//GEN-LAST:event_txtMatKhauMoiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhauJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenNhaCungCap;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblThem1;
    private javax.swing.JLabel lblTitleChinhSua;
    private javax.swing.JLabel lblTitleDiaChi;
    private GUI.Rounded pnlHuyBo;
    private GUI.Rounded pnlThayDoi;
    private javax.swing.JPanel pnlThongTinHoaDon;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtNhapLaiMatKhau;
    // End of variables declaration//GEN-END:variables
}
