/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DonHangDTO;
import DTO.KhachHangDTO;
import GUI.KhachHang.ChiTietKhachHangJPanel;
import GUI.Table.RenderTable;
import static GUI.TongQuanJPanel.customTable;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class KhachHangJPanel extends javax.swing.JPanel {
    Object[] columnNames ={"Mã khách hàng","Tên khách hàng","Email","Số điện thoại","Số đơn hàng"};
    /**
     * Creates new form NguoiDungJPanel
     */
    static DefaultTableModel listTableModel;
    public static KhachHangDTO currentKhachHang;
    public ArrayList<KhachHangDTO> arraySearch;
    public static ArrayList<DonHangDTO> currentDonHangList;
    public void ShowTable(JTable table,Object[] columnName){
        
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
    }  
    public static void fetchAll(){
        listTableModel.setRowCount(0);
        quanlycuahangsach.quanlycuahangsach.KhachHangBUS.KhachHangList.forEach(KhachHang ->{
            Vector row = new Vector();
            row.add(KhachHang.getMaKhachHang());
            row.add(KhachHang.getHoTen());
            row.add(KhachHang.getEmail());
            row.add(KhachHang.getSoDienThoai());
            row.add(KhachHang.getDiaChi());
            listTableModel.addRow(row);
        });
        tblKhachHang.setModel(listTableModel);
    }    
    public void setShadow(){
        
        pnlTblKhachHang.setShadow(1);
        
    } 
    private void getAdvancedSearch(){
        HashMap<String,String> advancedSearch = new HashMap<>();
        advancedSearch.put("MaKhachHang", txtTimKiemMaKhachHang.getText());
        advancedSearch.put("HoTen", txtTimKiemHoTen.getText());
        advancedSearch.put("Email",txtTimKiemEmail.getText());
        advancedSearch.put("SoDienThoai", txtTimKiemSDT.getText());
        arraySearch = quanlycuahangsach.quanlycuahangsach.KhachHangBUS.advancedSearch(advancedSearch);
        search();
    }    
    public void search(){
        if(arraySearch.isEmpty() && (txtTimKiemMaKhachHang.getText().equals("") && txtTimKiemHoTen.getText().equals("") && txtTimKiemEmail.getText().equals("") && txtTimKiemSDT.getText().equals(""))){
            fetchAll(); 
            return;
        }
        listTableModel.setRowCount(0);
        arraySearch.forEach(KhachHang ->{
            Vector row = new Vector();
            row.add(KhachHang.getMaKhachHang());
            row.add(KhachHang.getHoTen());
            row.add(KhachHang.getEmail());
            row.add(KhachHang.getSoDienThoai());
            row.add(KhachHang.getDiaChi());
            listTableModel.addRow(row);
        });
        tblKhachHang.setModel(listTableModel);
    }    
    public KhachHangJPanel() {
        initComponents();
        setShadow();
        customTable(tblKhachHang,scpKhachHang);
        ShowTable(tblKhachHang,columnNames);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlTimKiemHoTen = new GUI.Rounded();
        txtTimKiemHoTen = new javax.swing.JTextField();
        pnlTimKiemMaKhachHang = new GUI.Rounded();
        txtTimKiemMaKhachHang = new javax.swing.JTextField();
        pnlTimKiemEmail = new GUI.Rounded();
        txtTimKiemEmail = new javax.swing.JTextField();
        pnlTimKiemSDT = new GUI.Rounded();
        txtTimKiemSDT = new javax.swing.JTextField();
        pnlTblKhachHang = new GUI.Rounded();
        scpKhachHang = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }
        };

        setBackground(new java.awt.Color(238, 243, 247));
        setPreferredSize(new java.awt.Dimension(1040, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 52, 102));
        jLabel4.setText("Số điện thoại:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, 30));

        jLabel7.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 52, 102));
        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel6.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 52, 102));
        jLabel6.setText("Mã khách hàng:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 30));

        jLabel5.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 52, 102));
        jLabel5.setText("Tên khách hàng:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        pnlTimKiemHoTen.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemHoTen.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemHoTen.setFocusable(false);

        txtTimKiemHoTen.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemHoTen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemHoTen.setBorder(null);
        txtTimKiemHoTen.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtTimKiemHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHoTenKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemHoTenLayout = new javax.swing.GroupLayout(pnlTimKiemHoTen);
        pnlTimKiemHoTen.setLayout(pnlTimKiemHoTenLayout);
        pnlTimKiemHoTenLayout.setHorizontalGroup(
            pnlTimKiemHoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemHoTenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlTimKiemHoTenLayout.setVerticalGroup(
            pnlTimKiemHoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemHoTenLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(txtTimKiemHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        pnlTimKiemMaKhachHang.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemMaKhachHang.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemMaKhachHang.setFocusable(false);

        txtTimKiemMaKhachHang.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemMaKhachHang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaKhachHang.setBorder(null);
        txtTimKiemMaKhachHang.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtTimKiemMaKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaKhachHangKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemMaKhachHangLayout = new javax.swing.GroupLayout(pnlTimKiemMaKhachHang);
        pnlTimKiemMaKhachHang.setLayout(pnlTimKiemMaKhachHangLayout);
        pnlTimKiemMaKhachHangLayout.setHorizontalGroup(
            pnlTimKiemMaKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemMaKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlTimKiemMaKhachHangLayout.setVerticalGroup(
            pnlTimKiemMaKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemMaKhachHangLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        pnlTimKiemEmail.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemEmail.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemEmail.setFocusable(false);

        txtTimKiemEmail.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemEmail.setBorder(null);
        txtTimKiemEmail.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtTimKiemEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemEmailKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemEmailLayout = new javax.swing.GroupLayout(pnlTimKiemEmail);
        pnlTimKiemEmail.setLayout(pnlTimKiemEmailLayout);
        pnlTimKiemEmailLayout.setHorizontalGroup(
            pnlTimKiemEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlTimKiemEmailLayout.setVerticalGroup(
            pnlTimKiemEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemEmailLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(txtTimKiemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        pnlTimKiemSDT.setBackground(new java.awt.Color(238, 243, 247));
        pnlTimKiemSDT.setForeground(new java.awt.Color(202, 229, 246));
        pnlTimKiemSDT.setFocusable(false);

        txtTimKiemSDT.setBackground(new java.awt.Color(202, 229, 246));
        txtTimKiemSDT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemSDT.setBorder(null);
        txtTimKiemSDT.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtTimKiemSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemSDTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemSDTLayout = new javax.swing.GroupLayout(pnlTimKiemSDT);
        pnlTimKiemSDT.setLayout(pnlTimKiemSDTLayout);
        pnlTimKiemSDTLayout.setHorizontalGroup(
            pnlTimKiemSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemSDTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlTimKiemSDTLayout.setVerticalGroup(
            pnlTimKiemSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemSDTLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(txtTimKiemSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        pnlTblKhachHang.setBackground(new java.awt.Color(238, 243, 247));
        pnlTblKhachHang.setForeground(new java.awt.Color(238, 243, 247));

        tblKhachHang.setAutoCreateRowSorter(true);
        tblKhachHang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblKhachHang.setForeground(new java.awt.Color(24, 24, 24));
        tblKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblKhachHang.setFocusable(false);
        tblKhachHang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKhachHang.setRowHeight(20);
        tblKhachHang.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblKhachHang.setShowGrid(false);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        scpKhachHang.setViewportView(tblKhachHang);

        javax.swing.GroupLayout pnlTblKhachHangLayout = new javax.swing.GroupLayout(pnlTblKhachHang);
        pnlTblKhachHang.setLayout(pnlTblKhachHangLayout);
        pnlTblKhachHangLayout.setHorizontalGroup(
            pnlTblKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpKhachHang)
                .addContainerGap())
        );
        pnlTblKhachHangLayout.setVerticalGroup(
            pnlTblKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTblKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 973, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        int column = tblKhachHang.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblKhachHang.getRowHeight();

        if(row < tblKhachHang.getRowCount() && row >= 0 && column < tblKhachHang.getColumnCount() && column >= 0){
                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    currentKhachHang = quanlycuahangsach.quanlycuahangsach.KhachHangBUS.getByMaKhachHang((String) tblKhachHang.getModel().getValueAt(row, 0));
                    currentDonHangList = quanlycuahangsach.quanlycuahangsach.DonHangBUS.getByMaKhachHang(currentKhachHang.getMaKhachHang());
                    this.add(new ChiTietKhachHangJPanel());
                    this.validate();
                    this.repaint();
            }

        
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtTimKiemHoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHoTenKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemHoTenKeyReleased

    private void txtTimKiemEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemEmailKeyReleased
    getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemEmailKeyReleased

    private void txtTimKiemSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemSDTKeyReleased
       getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemSDTKeyReleased

    private void txtTimKiemMaKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaKhachHangKeyReleased
       getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaKhachHangKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private GUI.Rounded pnlTblKhachHang;
    private GUI.Rounded pnlTimKiemEmail;
    private GUI.Rounded pnlTimKiemHoTen;
    private GUI.Rounded pnlTimKiemMaKhachHang;
    private GUI.Rounded pnlTimKiemSDT;
    private javax.swing.JScrollPane scpKhachHang;
    private static javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtTimKiemEmail;
    private javax.swing.JTextField txtTimKiemHoTen;
    private javax.swing.JTextField txtTimKiemMaKhachHang;
    private javax.swing.JTextField txtTimKiemSDT;
    // End of variables declaration//GEN-END:variables
}
