/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.QuanLyDanhMuc.NhaCungCapJPanel;
import GUI.QuanLyDanhMuc.NhaXuatBanJPanel;
import GUI.QuanLyDanhMuc.TacGiaJPanel;
import GUI.QuanLyDanhMuc.TheLoaiJPanel;
import java.awt.BorderLayout;
import java.awt.Cursor;
import javax.swing.SwingUtilities;

/**
 *
 * @author admin
 */
public class QuanLyDanhMucJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyDanhMucJPanel
     */
    public QuanLyDanhMucJPanel() {
        initComponents();
        pnlNhaCungCap.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        pnlTacGia.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlTheLoai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        pnlNhaXuatBan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTacGia = new GUI.Rounded();
        jLabel2 = new javax.swing.JLabel();
        pnlTheLoai = new GUI.Rounded();
        jLabel1 = new javax.swing.JLabel();
        pnlNhaXuatBan = new GUI.Rounded();
        jLabel4 = new javax.swing.JLabel();
        pnlNhaCungCap = new GUI.Rounded();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTacGia.setBackground(new java.awt.Color(238, 243, 247));
        pnlTacGia.setForeground(new java.awt.Color(238, 243, 247));
        pnlTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTacGiaMouseClicked(evt);
            }
        });
        pnlTacGia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quanlydanhmuc/tacgia.png"))); // NOI18N
        pnlTacGia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        add(pnlTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 380, 260));

        pnlTheLoai.setBackground(new java.awt.Color(238, 243, 247));
        pnlTheLoai.setForeground(new java.awt.Color(238, 243, 247));
        pnlTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTheLoaiMouseClicked(evt);
            }
        });
        pnlTheLoai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quanlydanhmuc/theloai.png"))); // NOI18N
        pnlTheLoai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        add(pnlTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 380, 260));

        pnlNhaXuatBan.setBackground(new java.awt.Color(238, 243, 247));
        pnlNhaXuatBan.setForeground(new java.awt.Color(238, 243, 247));
        pnlNhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhaXuatBanMouseClicked(evt);
            }
        });
        pnlNhaXuatBan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quanlydanhmuc/nhaxuatban.png"))); // NOI18N
        pnlNhaXuatBan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        add(pnlNhaXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 347, 380, 260));

        pnlNhaCungCap.setBackground(new java.awt.Color(238, 243, 247));
        pnlNhaCungCap.setForeground(new java.awt.Color(238, 243, 247));
        pnlNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhaCungCapMouseClicked(evt);
            }
        });
        pnlNhaCungCap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quanlydanhmuc/nhacungcap.png"))); // NOI18N
        pnlNhaCungCap.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        add(pnlNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 347, 380, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTheLoaiMouseClicked
    if (SwingUtilities.isLeftMouseButton(evt)){ 
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new TheLoaiJPanel());
        this.validate();
        this.repaint();
    }
    }//GEN-LAST:event_pnlTheLoaiMouseClicked

    private void pnlNhaXuatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhaXuatBanMouseClicked
    if (SwingUtilities.isLeftMouseButton(evt)){ 
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new NhaXuatBanJPanel());
        this.validate();
        this.repaint();
    }
    }//GEN-LAST:event_pnlNhaXuatBanMouseClicked

    private void pnlTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTacGiaMouseClicked
    if (SwingUtilities.isLeftMouseButton(evt)){ 
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new TacGiaJPanel());
        this.validate();
        this.repaint();
    }
    }//GEN-LAST:event_pnlTacGiaMouseClicked

    private void pnlNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhaCungCapMouseClicked
    if (SwingUtilities.isLeftMouseButton(evt)){ 
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new NhaCungCapJPanel());
        this.validate();
        this.repaint();
    }
    }//GEN-LAST:event_pnlNhaCungCapMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private GUI.Rounded pnlNhaCungCap;
    private GUI.Rounded pnlNhaXuatBan;
    private GUI.Rounded pnlTacGia;
    private GUI.Rounded pnlTheLoai;
    // End of variables declaration//GEN-END:variables
}
