/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLyDanhMuc.Popup;

import DTO.NhaXuatBanDTO;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;


/**
 *
 * @author admin
 */
public class SuaJFrame extends javax.swing.JFrame {
    int option,xMouse,yMouse;
    /**
     * Creates new form ThemJFrame
     */
    public Object object;
    public SuaJFrame(){
        
    }
    public SuaJFrame(int option,Object data){
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(false);
        initComponents();
        this.option = option;
        this.setResizable(false);
        this.setLocationRelativeTo(null);        
        switch(this.option){
            case 1:
                lblTitleChinhSua.setText("Chỉnh sửa tác giả");
                lblMa.setText(((DTO.TacGiaDTO) data).getMaTacGia());
                lblTen.setText("Tên tác giả");
                lblIdMa.setText("Mã tác giả");
                txtTen.setText(((DTO.TacGiaDTO) data).getTenTacGia());
                this.object = new DTO.TacGiaDTO();
                this.object = (DTO.TacGiaDTO)data;
                break;
            case 2:
                lblTitleChinhSua.setText("Chỉnh sửa thể loại");
                txtTen.setText(((DTO.TheLoaiDTO) data).getTenTheLoai());
                lblMa.setText(((DTO.TheLoaiDTO) data).getMaTheLoai());
                lblTen.setText("Tên tác giả");
                lblIdMa.setText("Mã tác giả");
                this.object = new DTO.TheLoaiDTO();
                this.object = (DTO.TheLoaiDTO) data;
                break; 
            default:
                lblMa.setText(((DTO.NhaXuatBanDTO) data).getMaNhaXuatBan());
                txtTen.setText(((DTO.NhaXuatBanDTO) data).getTenNhaXuatBan());
                lblTen.setText("Tên nhà xuất bản");
                lblIdMa.setText("Mã tác giả");
                this.object = new DTO.NhaXuatBanDTO();
                this.object = (DTO.NhaXuatBanDTO) data;
                break;
        }
        pnlXacNhan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdMa = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblTitleChinhSua = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        pnlXacNhan = new GUI.Rounded();
        lblXacNhan = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(45, 47, 62));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdMa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblIdMa.setForeground(new java.awt.Color(0, 52, 102));
        lblIdMa.setText("Mã nhà xuất bản:");
        jPanel1.add(lblIdMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 33));

        lblTen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTen.setForeground(new java.awt.Color(0, 52, 102));
        lblTen.setText("Tên nhà xuất bản:");
        jPanel1.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        lblTitleChinhSua.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTitleChinhSua.setForeground(new java.awt.Color(0, 146, 242));
        lblTitleChinhSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleChinhSua.setText("Chỉnh sửa mã nhà xuất bản");
        jPanel1.add(lblTitleChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, 30));

        txtTen.setBackground(new java.awt.Color(202, 229, 246));
        txtTen.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtTen.setBorder(null);
        txtTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenKeyPressed(evt);
            }
        });
        jPanel1.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 20));

        pnlXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnlXacNhan.setForeground(new java.awt.Color(37, 213, 54));
        pnlXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXacNhanMouseClicked(evt);
            }
        });

        lblXacNhan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblXacNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXacNhan.setText("Xác nhận");
        lblXacNhan.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout pnlXacNhanLayout = new javax.swing.GroupLayout(pnlXacNhan);
        pnlXacNhan.setLayout(pnlXacNhanLayout);
        pnlXacNhanLayout.setHorizontalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlXacNhanLayout.setVerticalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXacNhan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnlXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        lblMa.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblMa.setForeground(new java.awt.Color(0, 146, 242));
        lblMa.setText("#123456");
        jPanel1.add(lblMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, 30));

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXacNhanMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            if(GUI.SweetAlert.SweetAlert.showSweetOption(this,"Thông báo","Xác nhận sửa?", 0)==1)
                edit();
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(true);
       this.dispose();
        }
    }//GEN-LAST:event_pnlXacNhanMouseClicked

    private void edit(){
      if (txtTen.getText().equals("")) {
            GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi", "Không được bỏ trống", 1);
            return;
        }
        String Error;
        switch (option) {

            case 1:
                ((DTO.TacGiaDTO) object).setTenTacGia(txtTen.getText());
                    
                Error = quanlycuahangsach.quanlycuahangsach.TacGiaBUS.Validation((DTO.TacGiaDTO) object);
                if (Error == null) {
                    quanlycuahangsach.quanlycuahangsach.TacGiaBUS.edit((DTO.TacGiaDTO) object);
                
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(true);
        this.dispose();

                } else {
                    GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi", Error, 1);
                }

                break;
            case 2:
                ((DTO.TheLoaiDTO) object).setTenTheLoai(txtTen.getText());    
                Error = quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.Validation((DTO.TheLoaiDTO) object);
                if (Error == null) {
                    quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.edit((DTO.TheLoaiDTO) object);
                
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(true);
        this.dispose();

                } else {
                    GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi", Error, 1);
                }

                break;
            default:
                ((DTO.NhaXuatBanDTO) object).setTenNhaXuatBan(txtTen.getText());  
                Error = quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.Validation((DTO.NhaXuatBanDTO) object);
                if (Error == null) {
                    quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.edit((DTO.NhaXuatBanDTO) object);
                
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg)).setEnabled(true);
        this.dispose();

                } else {
                    GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi", Error, 1);
                }

                break;
        }
    }
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x - xMouse, y-yMouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void txtTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (GUI.SweetAlert.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Xác nhận", "Lưu lại thay đổi?", 0) == 1) {
                edit();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdMa;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTitleChinhSua;
    private javax.swing.JLabel lblXacNhan;
    private GUI.Rounded pnlXacNhan;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
