/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLyDanhMuc.Popup;

import DTO.NhaCungCapDTO;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;


/**
 *
 * @author admin
 */
public class SuaNhaCungCapJFrame extends javax.swing.JFrame {
    int option,xMouse,yMouse;
    private NhaCungCapDTO currentNhaCungCap;
    /**
     * Creates new form ThemJFrame
     */

    public SuaNhaCungCapJFrame(){
        
    }
    public SuaNhaCungCapJFrame(NhaCungCapDTO NhaCungCap) {
        SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg).setEnabled(false);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        currentNhaCungCap = NhaCungCap;
        lblMaNhaCungCap.setText(currentNhaCungCap.getMaNhaCungCap());
        txtTenNhaCungCap.setText(currentNhaCungCap.getTenNhaCungCap());
        txtSoDienThoai.setText(currentNhaCungCap.getSoDienThoai());
        txtDiaChi.setText(currentNhaCungCap.getDiaChi());
        pnlXacNhan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    private void setCurrentNhaCungCap() {
        currentNhaCungCap.setMaNhaCungCap(lblMaNhaCungCap.getText());
        currentNhaCungCap.setTenNhaCungCap(txtTenNhaCungCap.getText());
        currentNhaCungCap.setSoDienThoai(txtSoDienThoai.getText());
        currentNhaCungCap.setDiaChi(txtDiaChi.getText());
    }

    private boolean isFill() {
        if (lblMaNhaCungCap.getText().equals("")) {
            return false;
        }
        if (txtTenNhaCungCap.getText().equals("")) {
            return false;
        }
        if (txtSoDienThoai.getText().equals("")) {
            return false;
        }
        if (txtDiaChi.getText().equals("")) {
            return false;
        }
        return true;
    }

    private void edit() {
        if (!isFill()) {
            GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi", "Không được bỏ trống", 1);
            return;
        }
        setCurrentNhaCungCap();
        String Error = quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.Validation(currentNhaCungCap);
        if (Error != null) {
            GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi", Error, 1);
            return;
        }
        quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.edit(currentNhaCungCap);
        SwingUtilities.getWindowAncestor(quanlycuahangsach.quanlycuahangsach.bg).setEnabled(true);
        this.dispose();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinHoaDon = new javax.swing.JPanel();
        lblTenNhaCungCap = new javax.swing.JLabel();
        lblTitleDiaChi = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblTitleMaNhaCungCap = new javax.swing.JLabel();
        lblMaNhaCungCap = new javax.swing.JLabel();
        pnlXacNhan = new GUI.Rounded();
        lblThem = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtTenNhaCungCap = new javax.swing.JTextField();
        lblTitleChinhSua = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(45, 47, 62));
        setUndecorated(true);

        pnlThongTinHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenNhaCungCap.setForeground(new java.awt.Color(0, 52, 102));
        lblTenNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenNhaCungCap.setText("Tên nhà cung cấp:");
        pnlThongTinHoaDon.add(lblTenNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblTitleDiaChi.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleDiaChi.setText("Địa chỉ:");
        pnlThongTinHoaDon.add(lblTitleDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblSoDienThoai.setForeground(new java.awt.Color(0, 52, 102));
        lblSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSoDienThoai.setText("Số điện thoại:");
        pnlThongTinHoaDon.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblTitleMaNhaCungCap.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleMaNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaNhaCungCap.setText("Mã nhà cung cấp:");
        pnlThongTinHoaDon.add(lblTitleMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        lblMaNhaCungCap.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblMaNhaCungCap.setForeground(new java.awt.Color(0, 146, 242));
        lblMaNhaCungCap.setText("MAGIAMGIA2020");
        pnlThongTinHoaDon.add(lblMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        pnlXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnlXacNhan.setForeground(new java.awt.Color(37, 213, 54));
        pnlXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXacNhanMouseClicked(evt);
            }
        });

        lblThem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("Xác nhận");

        javax.swing.GroupLayout pnlXacNhanLayout = new javax.swing.GroupLayout(pnlXacNhan);
        pnlXacNhan.setLayout(pnlXacNhanLayout);
        pnlXacNhanLayout.setHorizontalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThem, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlXacNhanLayout.setVerticalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlThongTinHoaDon.add(pnlXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 90, 40));

        txtSoDienThoai.setBackground(new java.awt.Color(202, 229, 246));
        txtSoDienThoai.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSoDienThoai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSoDienThoai.setBorder(null);
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyPressed(evt);
            }
        });
        pnlThongTinHoaDon.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 20));

        txtDiaChi.setBackground(new java.awt.Color(202, 229, 246));
        txtDiaChi.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChi.setBorder(null);
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyPressed(evt);
            }
        });
        pnlThongTinHoaDon.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 240, 20));

        txtTenNhaCungCap.setBackground(new java.awt.Color(202, 229, 246));
        txtTenNhaCungCap.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtTenNhaCungCap.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenNhaCungCap.setBorder(null);
        txtTenNhaCungCap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenNhaCungCapKeyPressed(evt);
            }
        });
        pnlThongTinHoaDon.add(txtTenNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 240, 20));

        lblTitleChinhSua.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTitleChinhSua.setForeground(new java.awt.Color(0, 146, 242));
        lblTitleChinhSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleChinhSua.setText("Chỉnh sửa nhà cung cấp");
        pnlThongTinHoaDon.add(lblTitleChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        pnlThongTinHoaDon.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXacNhanMouseClicked
       if (SwingUtilities.isLeftMouseButton(evt))
        if (GUI.SweetAlert.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Xác nhận", "Xác nhận thay đổi?", 1) == 1) {
            edit();
        }
    }//GEN-LAST:event_pnlXacNhanMouseClicked

    private void txtSoDienThoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDiaChi.requestFocus();
        }
    }//GEN-LAST:event_txtSoDienThoaiKeyPressed

    private void txtDiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (GUI.SweetAlert.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Xác nhận", "Lưu lại thay đổi?", 0) == 1) {
                edit();
            }
        }
    }//GEN-LAST:event_txtDiaChiKeyPressed

    private void txtTenNhaCungCapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenNhaCungCapKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSoDienThoai.requestFocus();
        }
    }//GEN-LAST:event_txtTenNhaCungCapKeyPressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNhaCungCapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaNhaCungCapJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMaNhaCungCap;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenNhaCungCap;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblTitleChinhSua;
    private javax.swing.JLabel lblTitleDiaChi;
    private javax.swing.JLabel lblTitleMaNhaCungCap;
    private javax.swing.JPanel pnlThongTinHoaDon;
    private GUI.Rounded pnlXacNhan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
