/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.NhanVien;

import DTO.AccountDTO;
import DTO.NhanVienDTO;
import GUI.QLNVJPanel;
import GUI.Sweet.SweetComboBox;
import static GUI.Sweet.SweetFileChooser.FileExists;
import static GUI.Sweet.SweetFileChooser.PATH_NHANVIEN;
import static GUI.Sweet.SweetImage.readImageFromFilePath;
import static GUI.Sweet.SweetImage.saveImage;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import quanlycuahangsach.Currency;

import static quanlycuahangsach.DateTime.TimestampToDateString;

/**
 *
 * @author admin
 */
public class ChiTietNhanVienJPanel extends javax.swing.JPanel {
    public ArrayList<javax.swing.AbstractButton> arrButton =new ArrayList<>();
    public ImageIcon imgAnhDaiDien;
    public static NhanVienDTO NhanVien = new NhanVienDTO();
    public static AccountDTO Account = new AccountDTO();
    public Currency currency;
 
    public void setRadioButton(){
        ButtonGroup groupGioiTinh = new javax.swing.ButtonGroup();  
        
        groupGioiTinh.add(radNam);
        groupGioiTinh.add(radNu);     
    }    
    public void setShadow(){
        pnlThongTin.setShadow(1);
        pnlTacVu.setShadow(1);
    }    
    /**
     * Creates new form ChiTietNhanVienJPanel
     */
    public ChiTietNhanVienJPanel(NhanVienDTO currentNhanVien,AccountDTO currentAccount) {
        this.NhanVien = currentNhanVien;
        this.Account = currentAccount;
        initComponents();
        setData();
        setShadow();
        setRadioButton();
        lblSua.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        
    }
    public void setRole(){
        String Role = Account.getRole();
        int i;
       for(i=0;i<Role.length()-2;i++){
           if(Role.codePointAt(i) == 49){
               arrButton.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png")));
           }arrButton.get(i).setEnabled(false);
       }
       for(;i<arrButton.size();i++){
           String Command = arrButton.get(i).getActionCommand();
           if(Command.equals(NhanVien.getGioiTinh())||Command.equals(NhanVien.getCaLam()) || Command.equals(NhanVien.getTrangThai())){
               arrButton.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png")));
               arrButton.get(i).setSelected(true);
       }arrButton.get(i).setEnabled(false);
       }
    }     
    public void setData(){
        
        lblMaNhanVien.setText(NhanVien.getMaNhanVien());
        lblHoTen.setText(NhanVien.getHoTen());
        lblDiaChi.setText(NhanVien.getDiaChi());
        lblNamSinh.setText(NhanVien.getNamSinh());
        lblSoDienThoai.setText(NhanVien.getSoDienThoai());
        lblTrangThai.setText(NhanVien.getTrangThai());
        lblCaLam.setText(NhanVien.getCaLam());
        
        String luong = currency.changeCurrency(NhanVien.getLuong());
        lblLuong.setText(luong+"đ");
        lblNgayVaoLam.setText(TimestampToDateString(NhanVien.getNgayVaoLam(),1));
        arrButton.add(cbxTongQuan);
        arrButton.add(cbxDonHang);
        arrButton.add(cbxSanPham);
        arrButton.add(cbxKhachHang);
        arrButton.add(cbxDoanhThu);
        arrButton.add(cbxThongKe);
        arrButton.add(cbxKhuyenMai);
        arrButton.add(cbxNhapHang);
        arrButton.add(cbxQuanLyNhanVien);
        arrButton.add(cbxQuanLyDanhMuc);
        arrButton.add(radNam);
        arrButton.add(radNu);
        setRole();         
        if (!FileExists(PATH_NHANVIEN + NhanVien.getImgSource())) {
            NhanVien.setImgSource("default.jpg");
            Image imageScale = readImageFromFilePath(PATH_NHANVIEN + NhanVien.getImgSource(), 168, 238);
            imgAnhDaiDien = new ImageIcon(imageScale);
            lblAnh.setIcon(imgAnhDaiDien);            
        }
        else{
        Image imageScale = readImageFromFilePath(PATH_NHANVIEN + NhanVien.getImgSource(), 168, 238);
        imgAnhDaiDien = new ImageIcon(imageScale);
        lblAnh.setIcon(imgAnhDaiDien);
        }
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTin = new GUI.Rounded();
        lblTitleTrangThai = new javax.swing.JLabel();
        lblLuong = new javax.swing.JLabel();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblDonHang2 = new javax.swing.JLabel();
        lblTrangThai2 = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblTitleHoTen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDiaChi = new javax.swing.JTextArea();
        lblDienThoai1 = new javax.swing.JLabel();
        lblDienThoai4 = new javax.swing.JLabel();
        lblNam = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        lblHoTen = new javax.swing.JLabel();
        radNu = new javax.swing.JRadioButton();
        lblNamSinh = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        lblCaLam = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        lblDonHang3 = new javax.swing.JLabel();
        lblDonHang4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe2 = new javax.swing.JLabel();
        lblSua = new javax.swing.JLabel();
        pnlTacVu = new GUI.Rounded();
        cbxTongQuan = new javax.swing.JCheckBox();
        cbxDonHang = new javax.swing.JCheckBox();
        cbxSanPham = new javax.swing.JCheckBox();
        cbxKhachHang = new javax.swing.JCheckBox();
        cbxDoanhThu = new javax.swing.JCheckBox();
        cbxThongKe = new javax.swing.JCheckBox();
        cbxKhuyenMai = new javax.swing.JCheckBox();
        cbxNhapHang = new javax.swing.JCheckBox();
        cbxQuanLyNhanVien = new javax.swing.JCheckBox();
        cbxQuanLyDanhMuc = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongTin.setBackground(new java.awt.Color(238, 243, 247));
        pnlThongTin.setForeground(new java.awt.Color(238, 243, 247));
        pnlThongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleTrangThai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleTrangThai.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleTrangThai.setText("Trạng thái:");
        pnlThongTin.add(lblTitleTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 30));

        lblLuong.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblLuong.setForeground(new java.awt.Color(24, 24, 24));
        lblLuong.setText("2000");
        pnlThongTin.add(lblLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, 30));

        lblNgayVaoLam.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNgayVaoLam.setText("Ngày vào làm");
        pnlThongTin.add(lblNgayVaoLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, 30));

        lblDonHang2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDonHang2.setForeground(new java.awt.Color(0, 52, 102));
        lblDonHang2.setText("Ca làm:");
        pnlThongTin.add(lblDonHang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, 30));

        lblTrangThai2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTrangThai2.setForeground(new java.awt.Color(0, 52, 102));
        lblTrangThai2.setText("Mã nhân viên:");
        pnlThongTin.add(lblTrangThai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        lblMaNhanVien.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(24, 24, 24));
        lblMaNhanVien.setText("NV1");
        pnlThongTin.add(lblMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 30));

        lblTitleHoTen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleHoTen.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleHoTen.setText("Họ và tên:");
        pnlThongTin.add(lblTitleHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 40));

        jScrollPane1.setBackground(new java.awt.Color(53, 55, 70));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lblDiaChi.setColumns(20);
        lblDiaChi.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblDiaChi.setLineWrap(true);
        lblDiaChi.setRows(5);
        lblDiaChi.setText("120 Công Chúa Ngọc Hân,\nPhường 12,Quận 11, TP Hồ Chí Minh\n");
        lblDiaChi.setBorder(null);
        lblDiaChi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblDiaChi.setEnabled(false);
        jScrollPane1.setViewportView(lblDiaChi);

        pnlThongTin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 70));

        lblDienThoai1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblDienThoai1.setForeground(new java.awt.Color(0, 52, 102));
        lblDienThoai1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDienThoai1.setText("Địa chỉ:");
        pnlThongTin.add(lblDienThoai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        lblDienThoai4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblDienThoai4.setForeground(new java.awt.Color(0, 52, 102));
        lblDienThoai4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDienThoai4.setText("Số điện thoại:");
        pnlThongTin.add(lblDienThoai4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 100, -1));

        lblNam.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNam.setForeground(new java.awt.Color(0, 52, 102));
        lblNam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNam.setText("Năm sinh:");
        pnlThongTin.add(lblNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        txtGioiTinh.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtGioiTinh.setForeground(new java.awt.Color(0, 52, 102));
        txtGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGioiTinh.setText("Giới tính:");
        pnlThongTin.add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        radNam.setBackground(new java.awt.Color(255, 255, 255));
        radNam.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        radNam.setForeground(new java.awt.Color(24, 24, 24));
        radNam.setText("Nam");
        radNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlThongTin.add(radNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 120, 70, -1));

        lblHoTen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(24, 24, 24));
        lblHoTen.setText("Phan Công Sơn");
        pnlThongTin.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, 20));

        radNu.setBackground(new java.awt.Color(255, 255, 255));
        radNu.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        radNu.setForeground(new java.awt.Color(24, 24, 24));
        radNu.setText("Nữ");
        radNu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlThongTin.add(radNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        lblNamSinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNamSinh.setForeground(new java.awt.Color(24, 24, 24));
        lblNamSinh.setText("2000");
        pnlThongTin.add(lblNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        lblSoDienThoai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(24, 24, 24));
        lblSoDienThoai.setText("0916375645");
        pnlThongTin.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        lblTrangThai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(24, 24, 24));
        lblTrangThai.setText("Còn làm");
        pnlThongTin.add(lblTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, 30));

        lblCaLam.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblCaLam.setForeground(new java.awt.Color(24, 24, 24));
        lblCaLam.setText("Phan Công Sơn");
        pnlThongTin.add(lblCaLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, 30));

        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setPreferredSize(new java.awt.Dimension(168, 238));
        pnlThongTin.add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 168, 238));

        lblDonHang3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDonHang3.setForeground(new java.awt.Color(0, 52, 102));
        lblDonHang3.setText("Lương:");
        pnlThongTin.add(lblDonHang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, 30));

        lblDonHang4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDonHang4.setForeground(new java.awt.Color(0, 52, 102));
        lblDonHang4.setText("Ngày vào làm:");
        pnlThongTin.add(lblDonHang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, 30));

        add(pnlThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 973, 370));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 52, 102));
        jLabel5.setText("Quyền:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 52, 102));
        jLabel4.setText("Thông tin cá nhân:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe2.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe2.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        lblSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSuaMouseClicked(evt);
            }
        });
        add(lblSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, -1, -1));

        pnlTacVu.setBackground(new java.awt.Color(238, 243, 247));
        pnlTacVu.setForeground(new java.awt.Color(238, 243, 247));
        pnlTacVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTongQuan.setBackground(new java.awt.Color(255, 255, 255));
        cbxTongQuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxTongQuan.setForeground(new java.awt.Color(0, 52, 102));
        cbxTongQuan.setText("Tổng quan");
        cbxTongQuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxTongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 134, 20));

        cbxDonHang.setBackground(new java.awt.Color(255, 255, 255));
        cbxDonHang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxDonHang.setForeground(new java.awt.Color(0, 52, 102));
        cbxDonHang.setText("Đơn hàng");
        cbxDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 100, 20));

        cbxSanPham.setBackground(new java.awt.Color(255, 255, 255));
        cbxSanPham.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxSanPham.setForeground(new java.awt.Color(0, 52, 102));
        cbxSanPham.setText("Sản phẩm");
        cbxSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 132, 20));

        cbxKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        cbxKhachHang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxKhachHang.setForeground(new java.awt.Color(0, 52, 102));
        cbxKhachHang.setText("Khách hàng");
        cbxKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        cbxKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhachHangActionPerformed(evt);
            }
        });
        pnlTacVu.add(cbxKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 20));

        cbxDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        cbxDoanhThu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxDoanhThu.setForeground(new java.awt.Color(0, 52, 102));
        cbxDoanhThu.setText("Doanh thu");
        cbxDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 134, 20));

        cbxThongKe.setBackground(new java.awt.Color(255, 255, 255));
        cbxThongKe.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxThongKe.setForeground(new java.awt.Color(0, 52, 102));
        cbxThongKe.setText("Thống kê");
        cbxThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 20));

        cbxKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        cbxKhuyenMai.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxKhuyenMai.setForeground(new java.awt.Color(0, 52, 102));
        cbxKhuyenMai.setText("Khuyến mãi");
        cbxKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 132, 20));

        cbxNhapHang.setBackground(new java.awt.Color(255, 255, 255));
        cbxNhapHang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxNhapHang.setForeground(new java.awt.Color(0, 52, 102));
        cbxNhapHang.setText("Nhập hàng");
        cbxNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 132, 20));

        cbxQuanLyNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        cbxQuanLyNhanVien.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxQuanLyNhanVien.setForeground(new java.awt.Color(0, 52, 102));
        cbxQuanLyNhanVien.setText("Quản lí nhân viên");
        cbxQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlTacVu.add(cbxQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, 20));

        cbxQuanLyDanhMuc.setBackground(new java.awt.Color(255, 255, 255));
        cbxQuanLyDanhMuc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxQuanLyDanhMuc.setForeground(new java.awt.Color(0, 52, 102));
        cbxQuanLyDanhMuc.setText("Quản lí danh mục");
        cbxQuanLyDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        cbxQuanLyDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxQuanLyDanhMucActionPerformed(evt);
            }
        });
        pnlTacVu.add(cbxQuanLyDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, 20));

        add(pnlTacVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 970, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new QLNVJPanel());
            this.validate();
            this.repaint();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void lblSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new SuaNhanVienJPanel());
            this.validate();
            this.repaint();
        }  
    }//GEN-LAST:event_lblSuaMouseClicked

    private void cbxKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKhachHangActionPerformed

    private void cbxQuanLyDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxQuanLyDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxQuanLyDanhMucActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxDoanhThu;
    private javax.swing.JCheckBox cbxDonHang;
    private javax.swing.JCheckBox cbxKhachHang;
    private javax.swing.JCheckBox cbxKhuyenMai;
    private javax.swing.JCheckBox cbxNhapHang;
    private javax.swing.JCheckBox cbxQuanLyDanhMuc;
    private javax.swing.JCheckBox cbxQuanLyNhanVien;
    private javax.swing.JCheckBox cbxSanPham;
    private javax.swing.JCheckBox cbxThongKe;
    private javax.swing.JCheckBox cbxTongQuan;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblCaLam;
    private javax.swing.JTextArea lblDiaChi;
    private javax.swing.JLabel lblDienThoai1;
    private javax.swing.JLabel lblDienThoai4;
    private javax.swing.JLabel lblDonHang2;
    private javax.swing.JLabel lblDonHang3;
    private javax.swing.JLabel lblDonHang4;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblNamSinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblQuayVe2;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblSua;
    private javax.swing.JLabel lblTitleHoTen;
    private javax.swing.JLabel lblTitleTrangThai;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangThai2;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlTacVu;
    private GUI.Rounded pnlThongTin;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JLabel txtGioiTinh;
    // End of variables declaration//GEN-END:variables
}
