/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KhachHang;

import DTO.ChiTietDonHangDTO;
import DTO.DonHangDTO;
import DTO.KhachHangDTO;
import DTO.SanPhamDTO;
import GUI.KhachHangJPanel;
import GUI.Table.RenderTable;
import GUI.Table.setColorForCell;
import static GUI.TongQuanJPanel.customTable;
import static GUI.TongQuanJPanel.setJTableColumnsWidth;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import static quanlycuahangsach.Currency.changeCurrency;
import quanlycuahangsach.DateTime;

/**
 *
 * @author admin
 */
public class ChiTietKhachHangJPanel extends javax.swing.JPanel {

    Object[] columnNames = {"Mã đơn hàng", "Ngày lập đơn", "Tạm tính", "Giảm giá", "Phí vận chuyển","Tổng tiền","Trạng thái"};
    public static ArrayList<ChiTietDonHangDTO> currentChiTietDonHangList;
    static DefaultTableModel listTableModel;
    public static DonHangDTO currentDonHang;
    /**
     * Creates new form DonHangJPanel
     */
    public void setColor() {
        for (int j = 0; j < tblDonHang.getRowCount(); j++) {
            for (int i = 3; i < tblDonHang.getColumnCount(); i++) {

                tblDonHang.getColumnModel().getColumn(i).setCellRenderer(new setColorForCell(tblDonHang, j, i));

            }

        }

    }

    public void ShowTable(JTable table, Object[] columnName) {
        
        table.setDefaultRenderer(Object.class, new RenderTable());

        listTableModel = new DefaultTableModel(columnNames,0);
        table.setModel(listTableModel);
        fetchAllDonHang();
    }

    public static void fetchAllDonHang(){
        KhachHangJPanel.currentDonHangList.forEach(DonHang->{
            Vector row =new Vector();
            row.add(DonHang.getMaDonHang());
            row.add(DateTime.TimestampToDateString(DonHang.getNgayXuat(),0));
            row.add(changeCurrency(DonHang.getTamTinh()));
            row.add(changeCurrency(DonHang.getGiamGia()));
            row.add(changeCurrency(DonHang.getPhiVanChuyen()));
            row.add(changeCurrency(DonHang.getTongTien()));
            row.add(getTrangThai(DonHang.getTrangThai()));
            listTableModel.addRow(row);
        });
        tblDonHang.setModel(listTableModel);
    }
        public static String getTrangThai(String MaTrangThai){
        return MaTrangThai.equals("1") ? "Thành Công" : "Hủy";
    }
    public String getGiaTriTrangThai(String currentTrangThai){
        return currentTrangThai.equals("Hủy") ? "0" : "1";
    }
    private void setData() {
        lblMaKhachHang.setText(GUI.KhachHangJPanel.currentKhachHang.getMaKhachHang());
        lblTenNguoiDung.setText(GUI.KhachHangJPanel.currentKhachHang.getHoTen());
        lblSoDienThoai.setText(GUI.KhachHangJPanel.currentKhachHang.getSoDienThoai());
        lblEmail.setText(GUI.KhachHangJPanel.currentKhachHang.getEmail());
        lblDiaChi.setText(GUI.KhachHangJPanel.currentKhachHang.getDiaChi());
        lblSoDonHang.setText(KhachHangJPanel.currentDonHangList.size()+"");
    }

    /**
     * Creates new form ChiTietKhachHangJPanel
     */
    public ChiTietKhachHangJPanel() {
        initComponents();
        customTable(tblDonHang, scpDonHang);
        ShowTable(tblDonHang, columnNames);
        setData();
        setColor();

        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();
        pnlThongTin = new GUI.Rounded();
        lblThongTinKhachHang = new javax.swing.JLabel();
        lblThongTinHoaDon1 = new javax.swing.JLabel();
        pnlThongTinHoaDon = new javax.swing.JPanel();
        lblTitleTenNguoiDung = new javax.swing.JLabel();
        lblTitleSoDonHang = new javax.swing.JLabel();
        lblTitleEmail = new javax.swing.JLabel();
        lblSoDonHang = new javax.swing.JLabel();
        lblTenNguoiDung = new javax.swing.JLabel();
        lblTitleHoTen = new javax.swing.JLabel();
        lblMaKhachHang = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTitleDiaChi = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblTitleSoDienThoai = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        scpDonHang = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnlThongTin.setBackground(new java.awt.Color(238, 243, 247));
        pnlThongTin.setForeground(new java.awt.Color(255, 255, 255));
        pnlThongTin.setPreferredSize(new java.awt.Dimension(920, 750));

        lblThongTinKhachHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinKhachHang.setForeground(new java.awt.Color(0, 146, 242));
        lblThongTinKhachHang.setText("Thông tin khách hàng");

        lblThongTinHoaDon1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinHoaDon1.setForeground(new java.awt.Color(0, 146, 242));
        lblThongTinHoaDon1.setText("Đơn hàng");

        pnlThongTinHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleTenNguoiDung.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblTitleTenNguoiDung.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleTenNguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleTenNguoiDung.setText("Tên người dùng:");
        pnlThongTinHoaDon.add(lblTitleTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblTitleSoDonHang.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleSoDonHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleSoDonHang.setText("Số đơn hàng:");
        pnlThongTinHoaDon.add(lblTitleSoDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        lblTitleEmail.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblTitleEmail.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleEmail.setText("Email:");
        pnlThongTinHoaDon.add(lblTitleEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblSoDonHang.setForeground(new java.awt.Color(24, 24, 24));
        lblSoDonHang.setText("12");
        pnlThongTinHoaDon.add(lblSoDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        lblTenNguoiDung.setForeground(new java.awt.Color(24, 24, 24));
        lblTenNguoiDung.setText("Phan Công Sơn");
        pnlThongTinHoaDon.add(lblTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lblTitleHoTen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblTitleHoTen.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleHoTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHoTen.setText("Mã khách hàng:");
        pnlThongTinHoaDon.add(lblTitleHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, -1));

        lblMaKhachHang.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblMaKhachHang.setForeground(new java.awt.Color(0, 146, 242));
        lblMaKhachHang.setText("MAKH123");
        pnlThongTinHoaDon.add(lblMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        lblEmail.setForeground(new java.awt.Color(24, 24, 24));
        lblEmail.setText("congsonlatoi@gmail.com");
        pnlThongTinHoaDon.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        lblTitleDiaChi.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblTitleDiaChi.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleDiaChi.setText("Địa chỉ:");
        pnlThongTinHoaDon.add(lblTitleDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblDiaChi.setForeground(new java.awt.Color(24, 24, 24));
        lblDiaChi.setText("120 Công chúa ngọc hân");
        pnlThongTinHoaDon.add(lblDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblTitleSoDienThoai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 1, 14)); // NOI18N
        lblTitleSoDienThoai.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleSoDienThoai.setText("Số điện thoại:");
        pnlThongTinHoaDon.add(lblTitleSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblSoDienThoai.setForeground(new java.awt.Color(24, 24, 24));
        lblSoDienThoai.setText("0916357534");
        pnlThongTinHoaDon.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        tblDonHang.setAutoCreateRowSorter(true);
        tblDonHang.setForeground(new java.awt.Color(24, 24, 24));
        tblDonHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDonHang.setFocusable(false);
        tblDonHang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDonHang.setRowHeight(25);
        tblDonHang.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangMouseClicked(evt);
            }
        });
        scpDonHang.setViewportView(tblDonHang);

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblThongTinHoaDon1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblThongTinKhachHang)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
            .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlThongTinLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scpDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblThongTinKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongTinHoaDon1)
                .addGap(434, 434, 434))
            .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addComponent(scpDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        add(pnlThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1000, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new KhachHangJPanel());
            this.validate();
            this.repaint();
        }// TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void tblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseClicked
        int column = tblDonHang.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblDonHang.getRowHeight();

        if (row < tblDonHang.getRowCount() && row >= 0 && column < tblDonHang.getColumnCount() && column >= 0) {
            currentDonHang =quanlycuahangsach.quanlycuahangsach.DonHangBUS.getByMaDonHang(tblDonHang.getModel().getValueAt(row, 0)+"");
            currentChiTietDonHangList = quanlycuahangsach.quanlycuahangsach.ChiTietDonHangBUS.getListChiTietByMaDonHang(currentDonHang.getMaDonHang());
                this.removeAll();
                this.setLayout(new BorderLayout());
                this.add(new ChiTietDonHangJPanel());
                this.validate();
                this.repaint();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblDonHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblSoDonHang;
    private javax.swing.JLabel lblTenNguoiDung;
    private javax.swing.JLabel lblThongTinHoaDon1;
    private javax.swing.JLabel lblThongTinKhachHang;
    private javax.swing.JLabel lblTitleDiaChi;
    private javax.swing.JLabel lblTitleEmail;
    private javax.swing.JLabel lblTitleHoTen;
    private javax.swing.JLabel lblTitleSoDienThoai;
    private javax.swing.JLabel lblTitleSoDonHang;
    private javax.swing.JLabel lblTitleTenNguoiDung;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlThongTin;
    private javax.swing.JPanel pnlThongTinHoaDon;
    private javax.swing.JScrollPane scpDonHang;
    private static javax.swing.JTable tblDonHang;
    // End of variables declaration//GEN-END:variables
}
