/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.DonHang;

import DTO.ChiTietDonHangDTO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.SwingUtilities;
import static quanlycuahangsach.Currency.changeCurrency;
import static quanlycuahangsach.Regexp.Replace;
import static quanlycuahangsach.Regexp.So;
import static quanlycuahangsach.Regexp.SoLuong;

/**
 *
 * @author admin
 */
public class SoLuong extends javax.swing.JFrame {
    /**
     * Creates new form SoLuongVaDonGiaJFrame
     */
    int xMouse,yMouse;
    ChiTietDonHangDTO currentChiTietDonHang;
    public SoLuong() {
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.DonHang.ThemSanPhamJFrame.tblSanPham)).setEnabled(false);
        initComponents();
        setLocationRelativeTo(null);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlSoLuongSanPhamNhap = new GUI.Rounded();
        txtSoLuongSanPhamBan = new javax.swing.JTextField();
        pnlThem = new GUI.Rounded();
        lblXacNhan = new javax.swing.JLabel();
        pnlHuy = new GUI.Rounded();
        lblHuy = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(238, 243, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 52, 102));
        jLabel10.setText("Số lượng sản phẩm mua:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        pnlSoLuongSanPhamNhap.setBackground(new java.awt.Color(45, 47, 62));
        pnlSoLuongSanPhamNhap.setForeground(new java.awt.Color(255, 255, 255));
        pnlSoLuongSanPhamNhap.setFocusable(false);

        txtSoLuongSanPhamBan.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSoLuongSanPhamBan.setForeground(new java.awt.Color(18, 18, 18));
        txtSoLuongSanPhamBan.setBorder(null);
        txtSoLuongSanPhamBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongSanPhamBanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlSoLuongSanPhamNhapLayout = new javax.swing.GroupLayout(pnlSoLuongSanPhamNhap);
        pnlSoLuongSanPhamNhap.setLayout(pnlSoLuongSanPhamNhapLayout);
        pnlSoLuongSanPhamNhapLayout.setHorizontalGroup(
            pnlSoLuongSanPhamNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSoLuongSanPhamNhapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSoLuongSanPhamBan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSoLuongSanPhamNhapLayout.setVerticalGroup(
            pnlSoLuongSanPhamNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSoLuongSanPhamNhapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSoLuongSanPhamBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlSoLuongSanPhamNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, 30));

        pnlThem.setBackground(new java.awt.Color(238, 243, 247));
        pnlThem.setForeground(new java.awt.Color(0, 146, 242));
        pnlThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThemMouseClicked(evt);
            }
        });
        pnlThem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblXacNhan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblXacNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXacNhan.setText("Thêm");
        pnlThem.add(lblXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 120, -1));

        jPanel1.add(pnlThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 50));

        pnlHuy.setBackground(new java.awt.Color(238, 243, 247));
        pnlHuy.setForeground(new java.awt.Color(255, 53, 53));
        pnlHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHuyMouseClicked(evt);
            }
        });
        pnlHuy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHuy.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblHuy.setForeground(new java.awt.Color(255, 255, 255));
        lblHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuy.setText("Hủy bỏ");
        pnlHuy.add(lblHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 120, -1));

        jPanel1.add(pnlHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 120, 50));

        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThemMouseClicked
        add();
    }//GEN-LAST:event_pnlThemMouseClicked

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y-yMouse);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void pnlHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseClicked
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.DonHang.ThemSanPhamJFrame.tblSanPham)).setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_pnlHuyMouseClicked

    private void add(){
    if(!SoLuong(txtSoLuongSanPhamBan.getText()) || txtSoLuongSanPhamBan.getText().equals("0")){
            GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi","Số lượng không hợp lệ",1);
            return;
        }
    else if(Integer.parseInt(txtSoLuongSanPhamBan.getText()) > Integer.parseInt(ThemSanPhamJFrame.SanPhamDangDuocChon.getSoLuong())){
    GUI.SweetAlert.SweetAlert.showSweetAlert(this, "Lỗi","Quá số lượng tồn kho",1);
            return;
    }
        currentChiTietDonHang = new ChiTietDonHangDTO();
        currentChiTietDonHang.setMaSanPham(ThemSanPhamJFrame.SanPhamDangDuocChon.getMaSanPham());
        currentChiTietDonHang.setDonGia(GUI.DonHang.ThemSanPhamJFrame.SanPhamDangDuocChon.getGia());
        currentChiTietDonHang.setSoLuong(txtSoLuongSanPhamBan.getText());
        currentChiTietDonHang.setThanhTien(changeCurrency(ThanhTien()));
        Vector data = new Vector();
       if(TaoDonHangJPanel.newChiTietDonHangList.size() > 0){
            for(int i=0;i<TaoDonHangJPanel.newChiTietDonHangList.size();i++){
                if(TaoDonHangJPanel.newChiTietDonHangList.get(i).getMaSanPham().equals(currentChiTietDonHang.getMaSanPham())){
                    TaoDonHangJPanel.newChiTietDonHangList.get(i).setSoLuong(currentChiTietDonHang.getSoLuong());
                    TaoDonHangJPanel.newChiTietDonHangList.get(i).setThanhTien(currentChiTietDonHang.getThanhTien());
                    for(int row=0;row<TaoDonHangJPanel.listTableModel.getRowCount();row++){
                        if(TaoDonHangJPanel.listTableModel.getValueAt(row, 0).equals(currentChiTietDonHang.getMaSanPham())){
                        TaoDonHangJPanel.listTableModel.setValueAt(currentChiTietDonHang.getSoLuong(), row,5);
                        TaoDonHangJPanel.listTableModel.setValueAt(currentChiTietDonHang.getThanhTien(),row,6);
                        System.out.println(TaoDonHangJPanel.newChiTietDonHangList.get(i).getThanhTien());
                        }
                    
                    }
                    ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.DonHang.ThemSanPhamJFrame.tblSanPham)).setEnabled(true);
            this.dispose();
                    return;
                }
            }
            }
            
            data.add(ThemSanPhamJFrame.SanPhamDangDuocChon.getMaSanPham());
            data.add(ThemSanPhamJFrame.SanPhamDangDuocChon.getTenSanPham());
            data.add(quanlycuahangsach.quanlycuahangsach.TacGiaBUS.getTenByMa(ThemSanPhamJFrame.SanPhamDangDuocChon.getMaTacGia()));
            data.add(quanlycuahangsach.quanlycuahangsach.TheLoaiBUS.getTenByMa(ThemSanPhamJFrame.SanPhamDangDuocChon.getMaTheLoai()));
            data.add(changeCurrency(ThemSanPhamJFrame.SanPhamDangDuocChon.getGia()));
            data.add(currentChiTietDonHang.getSoLuong());
            data.add(currentChiTietDonHang.getThanhTien());
            data.add("Xóa sản phẩm đã thêm");
            TaoDonHangJPanel.newChiTietDonHangList.add(currentChiTietDonHang);
            TaoDonHangJPanel.listTableModel.addRow(data); 
            TaoDonHangJPanel.setIcon();
            ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.DonHang.ThemSanPhamJFrame.tblSanPham)).setEnabled(true);
            this.dispose();
            ThemSanPhamJFrame.setIcon();
    }
    private String ThanhTien(){
        Double DonGia = Double.parseDouble(currentChiTietDonHang.getDonGia());
        Double SoLuong = Double.parseDouble(txtSoLuongSanPhamBan.getText());
        System.out.println(DonGia*SoLuong);
        return DonGia*SoLuong+"";
    }
    private void txtSoLuongSanPhamBanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongSanPhamBanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
            add();
    }//GEN-LAST:event_txtSoLuongSanPhamBanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHuy;
    private javax.swing.JLabel lblXacNhan;
    private GUI.Rounded pnlHuy;
    private GUI.Rounded pnlSoLuongSanPhamNhap;
    private GUI.Rounded pnlThem;
    private static javax.swing.JTextField txtSoLuongSanPhamBan;
    // End of variables declaration//GEN-END:variables
}
