/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLyDanhMuc;

import DTO.NhaCungCapDTO;
import GUI.QuanLyDanhMuc.Popup.SuaNhaCungCapJFrame;
import GUI.QuanLyDanhMucJPanel;
import GUI.Sweet.SweetFileChooser;
import GUI.SweetAlert.SweetAlert;
import GUI.Table.RenderTable;
import GUI.Table.setIconForCell;
import static GUI.TongQuanJPanel.customTable;
import static GUI.TongQuanJPanel.setJTableColumnsWidth;
import IO.Excel.NhaCungCapExcel;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class NhaCungCapJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TheLoaiJPanel
     */
    Object[] columnNames ={"Mã nhà cung cấp","Tên nhà cung cấp","Số điện thoại","Địa chỉ",""};
    public NhaCungCapDTO currentNhaCungCap = new NhaCungCapDTO();
    static DefaultTableModel listTableModel;
    
    public static void fetchAll(){
            String edit ="Sửa";
            listTableModel.setRowCount(0);
            quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.NhaCungCapList.forEach(NhaCungCap ->{
                Vector row = new Vector();
                row.add(NhaCungCap.getMaNhaCungCap());
                row.add(NhaCungCap.getTenNhaCungCap());
                row.add(NhaCungCap.getSoDienThoai());
                row.add(NhaCungCap.getDiaChi());
                row.add(edit);
                listTableModel.addRow(row);
            });
            tblNhaCungCap.setModel(listTableModel);
        }    
    public void setIcon(){
        
        for(int j = 0 ; j<tblNhaCungCap.getRowCount();j++){
            
                
                tblNhaCungCap.getColumnModel().getColumn(4).setCellRenderer(new setIconForCell(tblNhaCungCap,j,4));

            
            
        }
        
    }     
    public void setShadow(){
        pnlTheLoai.setShadow(1);
        pnlThemTheLoai.setShadow(1);
    }
    public void ShowTable(JTable table,Object[] columnName){ 
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
        lblMaNhaCungCap.setText(quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.getLatest());
    }    
    
    public NhaCungCapJPanel() {
        initComponents();
        customTable(tblNhaCungCap,scpNhaXuatBan);
        ShowTable(tblNhaCungCap,columnNames);
        setIcon();
        setJTableColumnsWidth(tblNhaCungCap,890,15,25,15,40,5); 
        setShadow();
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); 
        pnlThemTheLoai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();
        pnlThemTheLoai = new GUI.Rounded();
        lblTitleMaDonHang = new javax.swing.JLabel();
        lblTitleHoTen = new javax.swing.JLabel();
        lblMaNhaCungCap = new javax.swing.JLabel();
        pnlThem = new GUI.Rounded();
        lblHuyDon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        lblTitleHoTen1 = new javax.swing.JLabel();
        txtNhaCungCap = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        lblTitleHoTen2 = new javax.swing.JLabel();
        pnlNhapDuLieu = new GUI.Rounded();
        lblXuatHoaDon = new javax.swing.JLabel();
        pnlXuatDuLieu = new GUI.Rounded();
        lblXuatHoaDon1 = new javax.swing.JLabel();
        pnlTheLoai = new GUI.Rounded();
        scpNhaXuatBan = new javax.swing.JScrollPane();
        tblNhaCungCap = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblDonHang = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnlThemTheLoai.setBackground(new java.awt.Color(238, 243, 247));
        pnlThemTheLoai.setForeground(new java.awt.Color(238, 243, 247));
        pnlThemTheLoai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMaDonHang.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblTitleMaDonHang.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleMaDonHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaDonHang.setText("Mã nhà cung cấp:");
        pnlThemTheLoai.add(lblTitleMaDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblTitleHoTen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblTitleHoTen.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleHoTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHoTen.setText("Tên nhà cung cấp:");
        pnlThemTheLoai.add(lblTitleHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblMaNhaCungCap.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblMaNhaCungCap.setForeground(new java.awt.Color(0, 146, 242));
        lblMaNhaCungCap.setText("12345");
        pnlThemTheLoai.add(lblMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 47, -1, 20));

        pnlThem.setBackground(new java.awt.Color(255, 255, 255));
        pnlThem.setForeground(new java.awt.Color(0, 146, 242));
        pnlThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThemMouseClicked(evt);
            }
        });

        lblHuyDon.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblHuyDon.setForeground(new java.awt.Color(255, 255, 255));
        lblHuyDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuyDon.setText("Thêm");

        javax.swing.GroupLayout pnlThemLayout = new javax.swing.GroupLayout(pnlThem);
        pnlThem.setLayout(pnlThemLayout);
        pnlThemLayout.setHorizontalGroup(
            pnlThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThemLayout.createSequentialGroup()
                .addComponent(lblHuyDon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlThemLayout.setVerticalGroup(
            pnlThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHuyDon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlThemTheLoai.add(pnlThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 52, 102));
        jLabel3.setText("Thêm nhà cung cấp");
        pnlThemTheLoai.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 2, -1, 39));

        txtSoDienThoai.setBackground(new java.awt.Color(202, 229, 246));
        txtSoDienThoai.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(24, 24, 24));
        txtSoDienThoai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSoDienThoai.setBorder(null);
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyPressed(evt);
            }
        });
        pnlThemTheLoai.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 155, 30));

        lblTitleHoTen1.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblTitleHoTen1.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleHoTen1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHoTen1.setText("Số điện thoại:");
        pnlThemTheLoai.add(lblTitleHoTen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        txtNhaCungCap.setBackground(new java.awt.Color(202, 229, 246));
        txtNhaCungCap.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtNhaCungCap.setForeground(new java.awt.Color(24, 24, 24));
        txtNhaCungCap.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNhaCungCap.setBorder(null);
        txtNhaCungCap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhaCungCapKeyPressed(evt);
            }
        });
        pnlThemTheLoai.add(txtNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 86, 155, 30));

        txtDiaChi.setBackground(new java.awt.Color(202, 229, 246));
        txtDiaChi.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(24, 24, 24));
        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChi.setBorder(null);
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyPressed(evt);
            }
        });
        pnlThemTheLoai.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 155, 30));

        lblTitleHoTen2.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblTitleHoTen2.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleHoTen2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHoTen2.setText("Địa chỉ:");
        pnlThemTheLoai.add(lblTitleHoTen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 42, -1, -1));

        pnlNhapDuLieu.setBackground(new java.awt.Color(238, 243, 247));
        pnlNhapDuLieu.setForeground(new java.awt.Color(0, 146, 242));
        pnlNhapDuLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhapDuLieuMouseClicked(evt);
            }
        });

        lblXuatHoaDon.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblXuatHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblXuatHoaDon.setText("Nhập dữ liệu");

        javax.swing.GroupLayout pnlNhapDuLieuLayout = new javax.swing.GroupLayout(pnlNhapDuLieu);
        pnlNhapDuLieu.setLayout(pnlNhapDuLieuLayout);
        pnlNhapDuLieuLayout.setHorizontalGroup(
            pnlNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXuatHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNhapDuLieuLayout.setVerticalGroup(
            pnlNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXuatHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        pnlThemTheLoai.add(pnlNhapDuLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, -1, -1));

        pnlXuatDuLieu.setBackground(new java.awt.Color(238, 243, 247));
        pnlXuatDuLieu.setForeground(new java.awt.Color(0, 146, 242));
        pnlXuatDuLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXuatDuLieuMouseClicked(evt);
            }
        });

        lblXuatHoaDon1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblXuatHoaDon1.setForeground(new java.awt.Color(255, 255, 255));
        lblXuatHoaDon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXuatHoaDon1.setText("Xuất dữ liệu");

        javax.swing.GroupLayout pnlXuatDuLieuLayout = new javax.swing.GroupLayout(pnlXuatDuLieu);
        pnlXuatDuLieu.setLayout(pnlXuatDuLieuLayout);
        pnlXuatDuLieuLayout.setHorizontalGroup(
            pnlXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXuatHoaDon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlXuatDuLieuLayout.setVerticalGroup(
            pnlXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXuatHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        pnlThemTheLoai.add(pnlXuatDuLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 130, -1));

        add(pnlThemTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 973, 140));

        pnlTheLoai.setBackground(new java.awt.Color(238, 243, 247));
        pnlTheLoai.setForeground(new java.awt.Color(238, 243, 247));
        pnlTheLoai.setPreferredSize(new java.awt.Dimension(920, 750));

        scpNhaXuatBan.setForeground(new java.awt.Color(255, 255, 255));

        tblNhaCungCap.setAutoCreateRowSorter(true);
        tblNhaCungCap.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblNhaCungCap.setForeground(new java.awt.Color(18, 18, 18));
        tblNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblNhaCungCap.setFocusable(false);
        tblNhaCungCap.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblNhaCungCap.setRowHeight(25);
        tblNhaCungCap.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaCungCapMouseClicked(evt);
            }
        });
        scpNhaXuatBan.setViewportView(tblNhaCungCap);

        lblDonHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDonHang.setForeground(new java.awt.Color(0, 52, 102));
        lblDonHang.setText("Danh sách nhà xuất bản");

        javax.swing.GroupLayout pnlTheLoaiLayout = new javax.swing.GroupLayout(pnlTheLoai);
        pnlTheLoai.setLayout(pnlTheLoaiLayout);
        pnlTheLoaiLayout.setHorizontalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpNhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblDonHang)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTheLoaiLayout.setVerticalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDonHang)
                .addGap(18, 18, 18)
                .addComponent(scpNhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 970, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new QuanLyDanhMucJPanel());
            this.validate();
            this.repaint();
        }// TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void pnlThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThemMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt))
            add();
    }//GEN-LAST:event_pnlThemMouseClicked

    public void setCurrentNhaCungCap(){
        currentNhaCungCap.setMaNhaCungCap(lblMaNhaCungCap.getText());
        currentNhaCungCap.setTenNhaCungCap(txtNhaCungCap.getText());
        currentNhaCungCap.setDiaChi(txtDiaChi.getText());
        currentNhaCungCap.setSoDienThoai(txtSoDienThoai.getText());
    }
    private boolean isFill(){
    if(txtNhaCungCap.getText().equals("")) return false;
    if(txtSoDienThoai.getText().equals("")) return false;
    if(txtDiaChi.getText().equals("")) return false;
    return true;
    }
    public void add(){
        if(GUI.SweetAlert.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Xác nhận", "Thêm mới?",0)==1){
        if(!isFill()){GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi","Không được bỏ trống",1); return;}
        setCurrentNhaCungCap();
        if(quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.add(currentNhaCungCap))
        {
        fetchAll();
        GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Thành công","Thêm mới thành công",1);
        lblMaNhaCungCap.setText(quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.getLatest());
        fillBlank();
        }
        }
    }
    public void fillBlank(){
        txtNhaCungCap.setText("");
    txtSoDienThoai.setText("");
    txtDiaChi.setText("");
    }    
    private void tblNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaCungCapMouseClicked
        int column = tblNhaCungCap.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblNhaCungCap.getRowHeight();

        if(row < tblNhaCungCap.getRowCount() && row >= 0 && column < tblNhaCungCap.getColumnCount() && column >= 0){
                currentNhaCungCap = quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.getByMaNhaCungCap(tblNhaCungCap.getModel().getValueAt(row,0).toString());
                
            if(tblNhaCungCap.getValueAt(row,column).toString().equalsIgnoreCase("Sửa")){ 
                    
                           new SuaNhaCungCapJFrame(currentNhaCungCap).setVisible(true);

            }  
        }
    }//GEN-LAST:event_tblNhaCungCapMouseClicked

    private void txtNhaCungCapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhaCungCapKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           txtDiaChi.requestFocus();
       }
    }//GEN-LAST:event_txtNhaCungCapKeyPressed

    private void txtDiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           txtSoDienThoai.requestFocus();
       }
    }//GEN-LAST:event_txtDiaChiKeyPressed

    private void txtSoDienThoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(!isFill()){GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi","Không được bỏ trống",1); return;}
            add();
        }
    }//GEN-LAST:event_txtSoDienThoaiKeyPressed

    private void pnlNhapDuLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhapDuLieuMouseClicked
        try {
            String path = SweetFileChooser.ExcelFileChooser();
            if(path==null){
                SweetAlert.showSweetAlert(new JFrame(), "Lỗi", "Vui lòng chọn file phù hợp", 1);
                return;
            }
            NhaCungCapExcel.ImportExcelFile(path, 4).forEach(ncc->{
               if(quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.add(ncc)==false);
               ncc.setMaNhaCungCap(quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.getLatest());
               quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.add(ncc);
            });
            SweetAlert.showSweetAlert(new JFrame(), "Thành Công", "Nhập dữ liệu thành công", 0);
        } catch (IOException ex) {
            Logger.getLogger(NhaCungCapJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        fetchAll();
    }//GEN-LAST:event_pnlNhapDuLieuMouseClicked

    private void pnlXuatDuLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXuatDuLieuMouseClicked
            try {
            String path = SweetFileChooser.ExcelFileChooser();
            if(path==null){
                SweetAlert.showSweetAlert(new JFrame(), "Lỗi", "Vui lòng chọn file phù hợp", 1);
                return;
            }
            NhaCungCapExcel.ExportExcelFile(path, quanlycuahangsach.quanlycuahangsach.NhaCungCapBUS.NhaCungCapList);
            SweetAlert.showSweetAlert(new JFrame(), "Thành Công", "Xuất dữ liệu thành công", 0);
        } catch (IOException ex) {
            Logger.getLogger(NhaCungCapJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_pnlXuatDuLieuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDonHang;
    private javax.swing.JLabel lblHuyDon;
    private javax.swing.JLabel lblMaNhaCungCap;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblTitleHoTen;
    private javax.swing.JLabel lblTitleHoTen1;
    private javax.swing.JLabel lblTitleHoTen2;
    private javax.swing.JLabel lblTitleMaDonHang;
    private javax.swing.JLabel lblXuatHoaDon;
    private javax.swing.JLabel lblXuatHoaDon1;
    private GUI.Rounded pnlNhapDuLieu;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlTheLoai;
    private GUI.Rounded pnlThem;
    private GUI.Rounded pnlThemTheLoai;
    private GUI.Rounded pnlXuatDuLieu;
    private javax.swing.JScrollPane scpNhaXuatBan;
    private static javax.swing.JTable tblNhaCungCap;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
