/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLyDanhMuc;

import DTO.NhaXuatBanDTO;
import GUI.QuanLyDanhMuc.Popup.SuaJFrame;
import GUI.QuanLyDanhMucJPanel;
import GUI.Sweet.SweetFileChooser;
import GUI.SweetAlert.SweetAlert;
import GUI.Table.RenderTable;
import GUI.Table.setIconForCell;
import static GUI.TongQuanJPanel.customTable;
import static GUI.TongQuanJPanel.setJTableColumnsWidth;
import IO.Excel.NhaXuatBanExcel;
import IO.Excel.NhaXuatBanExcel;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class NhaXuatBanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TheLoaiJPanel
     */
    Object[] columnNames ={"Mã nhà xuât bản","Tên nhà xuất bản",""};
    public NhaXuatBanDTO currentNhaXuatBan = new NhaXuatBanDTO();
    static DefaultTableModel listTableModel;
    public void setIcon(){
        
        for(int j = 0 ; j<tblNhaXuatBan.getRowCount();j++){
            
                
                tblNhaXuatBan.getColumnModel().getColumn(2).setCellRenderer(new setIconForCell(tblNhaXuatBan,j,2));

            
            
        }
        
    }     
    public static void fetchAll(){
        String edit = "Sửa";
        listTableModel.setRowCount(0);
        quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.NhaXuatBanList.forEach(NhaXuatBan ->{
            Vector row = new Vector();
            row.add(NhaXuatBan.getMaNhaXuatBan());
            row.add(NhaXuatBan.getTenNhaXuatBan());
            row.add(edit);
            listTableModel.addRow(row);
        });
        tblNhaXuatBan.setModel(listTableModel);  
        
    }
    public void setShadow(){
        pnlTheLoai.setShadow(1);
        pnlThemTheLoai.setShadow(1);
    }
    public void ShowTable(JTable table,Object[] columnName){
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
        lblMaNhaXuatBan.setText(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getLatest());        
    }    
    
    public NhaXuatBanJPanel() {
        initComponents();
        customTable(tblNhaXuatBan,scpNhaXuatBan);
        ShowTable(tblNhaXuatBan,columnNames);
        setIcon();
        setJTableColumnsWidth(tblNhaXuatBan,958,25,65,10);
        setShadow();
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); 
        pnlThemTheLoai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();
        pnlThemTheLoai = new GUI.Rounded();
        lblTitleMaDonHang = new javax.swing.JLabel();
        lblTitleHoTen = new javax.swing.JLabel();
        lblMaNhaXuatBan = new javax.swing.JLabel();
        pnlXacNhan = new GUI.Rounded();
        lblHuyDon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNhaXuatBan = new javax.swing.JTextField();
        pnlXuatDuLieu = new GUI.Rounded();
        lblXuatHoaDon1 = new javax.swing.JLabel();
        pnlNhapDuLieu1 = new GUI.Rounded();
        lblXuatHoaDon2 = new javax.swing.JLabel();
        pnlTheLoai = new GUI.Rounded();
        scpNhaXuatBan = new javax.swing.JScrollPane();
        tblNhaXuatBan = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblDonHang = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 243, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlQuayVe.setBackground(new java.awt.Color(238, 243, 247));
        pnlQuayVe.setForeground(new java.awt.Color(0, 146, 242));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnlThemTheLoai.setBackground(new java.awt.Color(238, 243, 247));
        pnlThemTheLoai.setForeground(new java.awt.Color(238, 243, 247));

        lblTitleMaDonHang.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblTitleMaDonHang.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleMaDonHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaDonHang.setText("Mã nhà xuất bản:");

        lblTitleHoTen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblTitleHoTen.setForeground(new java.awt.Color(0, 52, 102));
        lblTitleHoTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHoTen.setText("Nhà xuất bản:");

        lblMaNhaXuatBan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblMaNhaXuatBan.setForeground(new java.awt.Color(0, 146, 242));
        lblMaNhaXuatBan.setText("12345");

        pnlXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnlXacNhan.setForeground(new java.awt.Color(0, 146, 242));
        pnlXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXacNhanMouseClicked(evt);
            }
        });

        lblHuyDon.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblHuyDon.setForeground(new java.awt.Color(255, 255, 255));
        lblHuyDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuyDon.setText("Thêm");

        javax.swing.GroupLayout pnlXacNhanLayout = new javax.swing.GroupLayout(pnlXacNhan);
        pnlXacNhan.setLayout(pnlXacNhanLayout);
        pnlXacNhanLayout.setHorizontalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXacNhanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHuyDon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlXacNhanLayout.setVerticalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHuyDon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 52, 102));
        jLabel3.setText("Thêm nhà xuất bản");

        txtNhaXuatBan.setBackground(new java.awt.Color(202, 229, 246));
        txtNhaXuatBan.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtNhaXuatBan.setForeground(new java.awt.Color(24, 24, 24));
        txtNhaXuatBan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNhaXuatBan.setBorder(null);
        txtNhaXuatBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhaXuatBanKeyPressed(evt);
            }
        });

        pnlXuatDuLieu.setBackground(new java.awt.Color(238, 243, 247));
        pnlXuatDuLieu.setForeground(new java.awt.Color(0, 146, 242));
        pnlXuatDuLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXuatDuLieuMouseClicked(evt);
            }
        });

        lblXuatHoaDon1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblXuatHoaDon1.setForeground(new java.awt.Color(255, 255, 255));
        lblXuatHoaDon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXuatHoaDon1.setText("Xuất dữ liệu");

        javax.swing.GroupLayout pnlXuatDuLieuLayout = new javax.swing.GroupLayout(pnlXuatDuLieu);
        pnlXuatDuLieu.setLayout(pnlXuatDuLieuLayout);
        pnlXuatDuLieuLayout.setHorizontalGroup(
            pnlXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXuatDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXuatHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlXuatDuLieuLayout.setVerticalGroup(
            pnlXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXuatHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        pnlNhapDuLieu1.setBackground(new java.awt.Color(238, 243, 247));
        pnlNhapDuLieu1.setForeground(new java.awt.Color(0, 146, 242));
        pnlNhapDuLieu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhapDuLieu1MouseClicked(evt);
            }
        });

        lblXuatHoaDon2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblXuatHoaDon2.setForeground(new java.awt.Color(255, 255, 255));
        lblXuatHoaDon2.setText("Nhập dữ liệu");

        javax.swing.GroupLayout pnlNhapDuLieu1Layout = new javax.swing.GroupLayout(pnlNhapDuLieu1);
        pnlNhapDuLieu1.setLayout(pnlNhapDuLieu1Layout);
        pnlNhapDuLieu1Layout.setHorizontalGroup(
            pnlNhapDuLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapDuLieu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXuatHoaDon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNhapDuLieu1Layout.setVerticalGroup(
            pnlNhapDuLieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXuatHoaDon2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlThemTheLoaiLayout = new javax.swing.GroupLayout(pnlThemTheLoai);
        pnlThemTheLoai.setLayout(pnlThemTheLoaiLayout);
        pnlThemTheLoaiLayout.setHorizontalGroup(
            pnlThemTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThemTheLoaiLayout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(pnlThemTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleHoTen)
                    .addComponent(lblTitleMaDonHang))
                .addGap(42, 42, 42)
                .addGroup(pnlThemTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThemTheLoaiLayout.createSequentialGroup()
                        .addComponent(lblMaNhaXuatBan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 591, Short.MAX_VALUE)
                        .addComponent(pnlXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThemTheLoaiLayout.createSequentialGroup()
                        .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlXuatDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlNhapDuLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(pnlThemTheLoaiLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlThemTheLoaiLayout.setVerticalGroup(
            pnlThemTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThemTheLoaiLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThemTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleMaDonHang)
                    .addComponent(lblMaNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThemTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleHoTen)
                    .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(pnlThemTheLoaiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlThemTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlXuatDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNhapDuLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlThemTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 973, 140));

        pnlTheLoai.setBackground(new java.awt.Color(238, 243, 247));
        pnlTheLoai.setForeground(new java.awt.Color(238, 243, 247));
        pnlTheLoai.setPreferredSize(new java.awt.Dimension(920, 750));

        scpNhaXuatBan.setForeground(new java.awt.Color(255, 255, 255));

        tblNhaXuatBan.setAutoCreateRowSorter(true);
        tblNhaXuatBan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblNhaXuatBan.setForeground(new java.awt.Color(18, 18, 18));
        tblNhaXuatBan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblNhaXuatBan.setFocusable(false);
        tblNhaXuatBan.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblNhaXuatBan.setRowHeight(25);
        tblNhaXuatBan.setSelectionBackground(new java.awt.Color(152, 210, 248));
        tblNhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaXuatBanMouseClicked(evt);
            }
        });
        scpNhaXuatBan.setViewportView(tblNhaXuatBan);

        lblDonHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDonHang.setForeground(new java.awt.Color(0, 52, 102));
        lblDonHang.setText("Danh sách nhà xuất bản");

        javax.swing.GroupLayout pnlTheLoaiLayout = new javax.swing.GroupLayout(pnlTheLoai);
        pnlTheLoai.setLayout(pnlTheLoaiLayout);
        pnlTheLoaiLayout.setHorizontalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpNhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblDonHang)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTheLoaiLayout.setVerticalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDonHang)
                .addGap(18, 18, 18)
                .addComponent(scpNhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 970, 420));
    }// </editor-fold>//GEN-END:initComponents

    public void setCurrentNhaXuatBan(){
        currentNhaXuatBan.setMaNhaXuatBan(lblMaNhaXuatBan.getText());
        currentNhaXuatBan.setTenNhaXuatBan(txtNhaXuatBan.getText());
    }
    private boolean isFill(){
    if(txtNhaXuatBan.getText().equals("")) return false;

    return true;
    }
    public void add(){
        if(GUI.SweetAlert.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Xác nhận", "Thêm mới?",0)==1){
        if(!isFill()){GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi","Không được bỏ trống",1); return;}
        setCurrentNhaXuatBan();
        if(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.add(currentNhaXuatBan))
        {
        fetchAll();
        GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Thành công","Thêm mới thành công",1);
        lblMaNhaXuatBan.setText(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getLatest());
        fillBlank();
        }
        }
    }
    public void fillBlank(){
        txtNhaXuatBan.setText("");
    }  
    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new QuanLyDanhMucJPanel());
            this.validate();
            this.repaint();
        }// TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void pnlXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXacNhanMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt))
            add();
        
    }//GEN-LAST:event_pnlXacNhanMouseClicked

    private void tblNhaXuatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaXuatBanMouseClicked
        int column = tblNhaXuatBan.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblNhaXuatBan.getRowHeight();

        if(row < tblNhaXuatBan.getRowCount() && row >= 0 && column < tblNhaXuatBan.getColumnCount() && column >= 0){

                currentNhaXuatBan = quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getByMaNhaXuatBan(tblNhaXuatBan.getModel().getValueAt(row,0).toString());
            

        }
            if(tblNhaXuatBan.getValueAt(row,column).toString().equalsIgnoreCase("Sửa")){ 
                           new SuaJFrame(0,currentNhaXuatBan).setVisible(true);

            }         
    }//GEN-LAST:event_tblNhaXuatBanMouseClicked

    private void txtNhaXuatBanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhaXuatBanKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(!isFill()){GUI.SweetAlert.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi","Không được bỏ trống",1); return;}
            add();
        }
    }//GEN-LAST:event_txtNhaXuatBanKeyPressed

    private void pnlXuatDuLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXuatDuLieuMouseClicked
            try {
            String path = SweetFileChooser.ExcelFileChooser();
            if(path==null){
                SweetAlert.showSweetAlert(new JFrame(), "Lỗi", "Vui lòng chọn file phù hợp", 1);
                return;
            }
            NhaXuatBanExcel.ExportExcelFile(path, quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.NhaXuatBanList);
            SweetAlert.showSweetAlert(new JFrame(), "Thành Công", "Xuất dữ liệu thành công", 0);
        } catch (IOException ex) {
            Logger.getLogger(NhaXuatBanJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnlXuatDuLieuMouseClicked

    private void pnlNhapDuLieu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhapDuLieu1MouseClicked
        try {
            String path = SweetFileChooser.ExcelFileChooser();
            if(path==null){
                SweetAlert.showSweetAlert(new JFrame(), "Lỗi", "Vui lòng chọn file phù hợp", 1);
                return;
            }
            NhaXuatBanExcel.ImportExcelFile(path, 2).forEach(nxb->{
               if(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.add(nxb)==false);
               nxb.setMaNhaXuatBan(quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.getLatest());
               quanlycuahangsach.quanlycuahangsach.NhaXuatBanBUS.add(nxb);
            });
            SweetAlert.showSweetAlert(new JFrame(), "Thành Công", "Nhập dữ liệu thành công", 0);
        } catch (IOException ex) {
            Logger.getLogger(NhaXuatBanJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        fetchAll();
    }//GEN-LAST:event_pnlNhapDuLieu1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDonHang;
    private javax.swing.JLabel lblHuyDon;
    private javax.swing.JLabel lblMaNhaXuatBan;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblTitleHoTen;
    private javax.swing.JLabel lblTitleMaDonHang;
    private javax.swing.JLabel lblXuatHoaDon1;
    private javax.swing.JLabel lblXuatHoaDon2;
    private GUI.Rounded pnlNhapDuLieu1;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlTheLoai;
    private GUI.Rounded pnlThemTheLoai;
    private GUI.Rounded pnlXacNhan;
    private GUI.Rounded pnlXuatDuLieu;
    private javax.swing.JScrollPane scpNhaXuatBan;
    private static javax.swing.JTable tblNhaXuatBan;
    private javax.swing.JTextField txtNhaXuatBan;
    // End of variables declaration//GEN-END:variables
}
